module

public import RequestProject.TheoremA.Defs

/-!
# Groups of type `FP₁` are finitely generated

`IsFP.fg : IsFP 1 G → Group.FG G` (hence also for every `IsFP n G` with `1 ≤ n`).

Proof.  Let `ε : ℤ[G]^c → ℤ` be the augmentation of a partial resolution of length one and
`k_j = d(e_j)` the finitely many generators of `ker ε = range d`.  Pick `u` with `ε u = 1`, and
let `H` be the subgroup generated by all group elements occurring in `u` and in the `k_j`.
The `ℤ`-linear map `β : ℤ[G]^c → ℤ[G ⧸ H]`, `g • e_i ↦ ε(e_i) [gH]`, commutes with translations,
vanishes on each `k_j` (their coordinates are supported in `H`, and `ε k_j = 0`), hence on
`ker ε`, and sends `u` to `[H]`.  For `g ∈ G`, `g • u - u ∈ ker ε`, so `[gH] = [H]`, i.e. `g ∈ H`.
-/

@[expose] public section

namespace TheoremA

variable {G : Type*} [Group G]

section CosetTest

variable (H : Subgroup G)

/-- `ℤ[G] → ℤ[G ⧸ H]` induced by the projection. -/
noncomputable abbrev cosetMap : MonoidAlgebra ℤ G →+ ((G ⧸ H) →₀ ℤ) :=
  Finsupp.mapDomain.addMonoidHom (QuotientGroup.mk : G → G ⧸ H)

/-- Left translation by `g` on `ℤ[G ⧸ H]`. -/
noncomputable abbrev cosetTransl (g : G) : ((G ⧸ H) →₀ ℤ) →+ ((G ⧸ H) →₀ ℤ) :=
  Finsupp.mapDomain.addMonoidHom (fun a : G ⧸ H => g • a)

theorem cosetMap_single (a : G) (m : ℤ) :
    cosetMap H (MonoidAlgebra.single a m) = Finsupp.single (a : G ⧸ H) m :=
  Finsupp.mapDomain_single

theorem cosetMap_of_mul (g : G) (f : MonoidAlgebra ℤ G) :
    cosetMap H (MonoidAlgebra.of ℤ G g * f) = cosetTransl H g (cosetMap H f) := by
  induction f using MonoidAlgebra.induction_on with
  | hM a =>
    rw [MonoidAlgebra.of_apply, MonoidAlgebra.of_apply, MonoidAlgebra.single_mul_single, one_mul,
      cosetMap_single, cosetMap_single]
    simp [cosetTransl, MulAction.Quotient.smul_mk]
  | hadd x y hx hy => rw [mul_add, map_add, map_add, hx, hy, map_add]
  | hsmul r x hx => rw [mul_smul_comm, map_zsmul, map_zsmul, hx, map_zsmul]

variable {k : ℕ} (w : Fin k → ℤ)

/-- The test map `β(v) = ∑ i, w i • [v i mod H]`. -/
noncomputable def cosetTest : FreeMod G k →+ ((G ⧸ H) →₀ ℤ) :=
  ∑ i, w i • (cosetMap H).comp (Pi.evalAddMonoidHom (fun _ => MonoidAlgebra ℤ G) i)

theorem cosetTest_apply (v : FreeMod G k) :
    cosetTest H w v = ∑ i, w i • cosetMap H (v i) := by
  simp [cosetTest, AddMonoidHom.finset_sum_apply]

theorem cosetTest_of_smul (g : G) (v : FreeMod G k) :
    cosetTest H w (MonoidAlgebra.of ℤ G g • v) = cosetTransl H g (cosetTest H w v) := by
  simp only [cosetTest_apply, Pi.smul_apply, smul_eq_mul, cosetMap_of_mul, map_sum, map_zsmul]

theorem cosetTest_smul_eq_zero {v : FreeMod G k} (hv : cosetTest H w v = 0)
    (r : MonoidAlgebra ℤ G) : cosetTest H w (r • v) = 0 := by
  induction r using MonoidAlgebra.induction_on with
  | hM g => rw [cosetTest_of_smul, hv, map_zero]
  | hadd x y hx hy => rw [add_smul, map_add, hx, hy, add_zero]
  | hsmul m x hx => rw [smul_assoc, map_zsmul, hx, smul_zero]

end CosetTest

open Classical in
/-- The group elements occurring in a vector of `ℤ[G]^k`. -/
noncomputable def vecSupport {k : ℕ} (v : FreeMod G k) : Finset G :=
  Finset.univ.biUnion fun i => (v i).support

open Classical in
theorem mem_vecSupport {k : ℕ} {v : FreeMod G k} {i : Fin k} {a : G} (ha : a ∈ (v i).support) :
    a ∈ vecSupport v :=
  Finset.mem_biUnion.2 ⟨i, Finset.mem_univ _, ha⟩

/-- On vectors supported in `H`, the test map is `ε(v) [H]`. -/
theorem cosetTest_of_support_le {k : ℕ} (ε : FreeMod G k →+ ℤ)
    (hε : ∀ (g : G) (x : FreeMod G k), ε (MonoidAlgebra.of ℤ G g • x) = ε x)
    (H : Subgroup G) (v : FreeMod G k) (hv : ∀ a ∈ vecSupport v, a ∈ H) :
    cosetTest H (fun i => ε (Pi.single i 1)) v = Finsupp.single ((1 : G) : G ⧸ H) (ε v) := by
  classical
  have hdecomp : v = ∑ i, ∑ a ∈ (v i).support,
      Pi.single i (Finsupp.single a (v i a) : MonoidAlgebra ℤ G) := by
    conv_lhs => rw [← Finset.univ_sum_single v]
    refine Finset.sum_congr rfl fun i _ => ?_
    conv_lhs => rw [← Finsupp.sum_single (v i)]
    rw [Finsupp.sum]
    exact map_sum (AddMonoidHom.single (fun _ => MonoidAlgebra ℤ G) i) _ _
  have hterm : ∀ i, ∀ a ∈ H, ∀ m : ℤ,
      cosetTest H (fun i => ε (Pi.single i 1))
        (Pi.single i (Finsupp.single a m : MonoidAlgebra ℤ G)) =
      Finsupp.single ((1 : G) : G ⧸ H)
        (ε (Pi.single i (Finsupp.single a m : MonoidAlgebra ℤ G))) := by
    intro i a ha m
    have hsplit : (Pi.single i (Finsupp.single a m : MonoidAlgebra ℤ G) : FreeMod G k) =
        m • (MonoidAlgebra.of ℤ G a • (Pi.single i 1 : FreeMod G k)) := by
      ext j : 1
      by_cases hj : j = i
      · subst hj
        simp [MonoidAlgebra.of_apply]
      · simp [hj]
    have haH : ((a : G) : G ⧸ H) = ((1 : G) : G ⧸ H) :=
      QuotientGroup.eq.2 (by simpa using ha)
    have h2 : (MonoidAlgebra.of ℤ G a • (Pi.single i 1 : FreeMod G k)) =
        Pi.single i (MonoidAlgebra.of ℤ G a) := by
      ext j : 1
      by_cases hj : j = i
      · subst hj; simp
      · simp [hj]
    rw [hsplit, map_zsmul, map_zsmul, hε, cosetTest_apply, h2,
      Finset.sum_eq_single i (fun b _ hb => by simp [hb]) (by simp)]
    simp [MonoidAlgebra.of_apply, cosetMap_single, haH, Finsupp.smul_single, mul_comm]
  conv_lhs => rw [hdecomp]
  conv_rhs => rw [hdecomp]
  simp only [map_sum, Finsupp.single_finset_sum]
  refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun a ha => ?_
  exact hterm i a (hv a (mem_vecSupport ha)) _

/-- **`FP₁` groups are finitely generated.** -/
theorem IsFP.fg (h : IsFP 1 G) : Group.FG G := by
  classical
  obtain ⟨c, d, ε, hε, hsurj, hker, -⟩ := h
  have hker' := hker one_pos
  obtain ⟨u, hu⟩ := hsurj 1
  let kk : Fin (c 1) → FreeMod G (c 0) := fun j => d 0 (Pi.single j 1)
  let A : Finset G := vecSupport u ∪ Finset.univ.biUnion fun j => vecSupport (kk j)
  let H : Subgroup G := Subgroup.closure (A : Set G)
  let w : Fin (c 0) → ℤ := fun i => ε (Pi.single i 1)
  have hmemker : ∀ y ∈ LinearMap.range (d 0), ε y = 0 := by
    intro y hy
    have : y ∈ ε.ker := by rw [hker']; exact hy
    exact this
  have hkk : ∀ j, cosetTest H w (kk j) = 0 := by
    intro j
    rw [cosetTest_of_support_le ε hε H (kk j) (fun a ha => Subgroup.subset_closure
      (Finset.mem_union_right _ (Finset.mem_biUnion.2 ⟨j, Finset.mem_univ _, ha⟩))),
      hmemker _ (LinearMap.mem_range_self _ _), Finsupp.single_zero]
  have hrange : ∀ z : FreeMod G (c 1), cosetTest H w (d 0 z) = 0 := by
    intro z
    have hz : z = ∑ j, z j • (Pi.single j 1 : FreeMod G (c 1)) := by
      ext j : 1
      simp [Finset.sum_apply, Pi.single_apply]
    rw [hz, map_sum, map_sum]
    refine Finset.sum_eq_zero fun j _ => ?_
    rw [map_smul]
    exact cosetTest_smul_eq_zero H w (hkk j) _
  have hu' : cosetTest H w u = Finsupp.single ((1 : G) : G ⧸ H) 1 := by
    rw [cosetTest_of_support_le ε hε H u (fun a ha => Subgroup.subset_closure
      (Finset.mem_union_left _ ha)), hu]
  have hall : ∀ g : G, g ∈ H := by
    intro g
    have h0 : ε (MonoidAlgebra.of ℤ G g • u - u) = 0 := by rw [map_sub, hε, sub_self]
    have h1 : MonoidAlgebra.of ℤ G g • u - u ∈ LinearMap.range (d 0) := by
      have : MonoidAlgebra.of ℤ G g • u - u ∈ ε.ker := h0
      rw [hker'] at this
      exact this
    obtain ⟨z, hz⟩ := h1
    have h2 := hrange z
    rw [hz, map_sub, cosetTest_of_smul, hu', sub_eq_zero] at h2
    simp only [cosetTransl, Finsupp.mapDomain.addMonoidHom_apply, Finsupp.mapDomain_single] at h2
    have h3 := (Finsupp.single_left_inj one_ne_zero).1 h2
    rw [MulAction.Quotient.smul_mk, smul_eq_mul, mul_one, QuotientGroup.eq] at h3
    simpa using h3
  exact Group.fg_iff.2 ⟨A, eq_top_iff.2 fun g _ => hall g, A.finite_toSet⟩

/-- `IsFP n G` with `1 ≤ n` implies `IsFP 1 G`. -/
theorem IsFP.one_of_le {n : ℕ} (h : IsFP n G) (hn : 1 ≤ n) : IsFP 1 G := by
  obtain ⟨c, d, ε, hε, hsurj, hker, -⟩ := h
  exact ⟨c, d, ε, hε, hsurj, fun _ => hker (by omega), fun i hi => by omega⟩

/-- Groups of type `FP_n` with `1 ≤ n` are finitely generated. -/
theorem IsFP.fg_of_le {n : ℕ} (h : IsFP n G) (hn : 1 ≤ n) : Group.FG G :=
  (h.one_of_le hn).fg

end TheoremA
