module

public import RequestProject.TheoremA.Leary.Heap
public import RequestProject.TheoremA.Leary.SourceBridge
public import RequestProject.TheoremA.Leary.Flagness

/-!
# Unconditional separation for `flagL`

For every integer `n ≠ 0` we construct a homomorphism `ψ n : P → Perm (Pos × Fin 5)` (where
`P = flagL.PGrp` is the group of short relations and `Pos` is the heap model of the right-angled
Artin group `A_L` of the 1-skeleton of `flagL`, see `Leary/Heap.lean`) such that

* `ψ n ∘ ρ_m = 1` for every `m ≠ n` (`psi_comp_rho`);
* `ψ n (ρ_n [γ]) ≠ 1` (`psi_rho_loop_ne_one`).

Here a directed edge `a : u → v` acts on a position `p` by `p ↦ u v⁻¹ · p`, and on the fibre
`Fin 5` over a position of height `n` by the `S₅`-label (`flagPerm`) of the edge of `flagL` joining
the last-letter vertices of the old and the new position.  The last-letter vertices of all the
positions visited while multiplying by elements of a clique subgroup lie in one simplex
(`Heap.ivert_adj_of_rest_eq`), which gives both the relations of `P` and the triviality of the
powered loops `ρ_m`, `m ≠ n` (all their positions are coned off by a last letter of the apex
`u₀⁻ᵐ · p`, which is not the identity because its height `n - m` is nonzero).  At the apex of
height `0` the fibre transport along the `n`-th powered loop is the `S₅`-image of `γ`, which is
the 3-cycle `(0 2 4)`.

Consequently `flagSeparation : FlagSeparation` holds unconditionally, and so does
`learyDetectionFlag : LearyDetectionFlag`.
-/

@[expose] public section

namespace TheoremA.Leary.Detection

open Classical EdgeData Heap Subgroup

/-- The 1-skeleton of `flagL` is a simple graph. -/
theorem flagL_isGraph : IsGraph flagL.Adj where
  symm := by
    rintro a b ⟨e, rfl, rfl⟩
    exact ⟨flagL.rev e, flagL_rev_src e, flagL_rev_tgt e⟩
  irrefl := by
    rintro a ⟨e, h1, h2⟩
    exact flagL_no_loop e (h1.trans h2.symm)

/-- Positions. -/
abbrev PosL := Pos flagL.Adj

/-- The vertex generators. -/
noncomputable abbrev g (v : Fin flagL.nv) : Equiv.Perm PosL := gen flagL_isGraph v

/-- An edge `a : u → v` acts as `u v⁻¹`. -/
noncomputable def beta (a : Fin flagL.m) : Equiv.Perm PosL :=
  g (flagL.src a) * (g (flagL.tgt a))⁻¹

/-- A chosen last-letter vertex. -/
noncomputable def cv (p : PosL) : Fin flagL.nv :=
  if h : (Ivert flagL.Adj p.1).Nonempty then h.some else flagL.root

/-- The `S₅`-label of the edge `x → y` (`1` if there is none). -/
noncomputable def tau (x y : Fin flagL.nv) : Equiv.Perm (Fin 5) :=
  if h : flagL.Adj x y then flagPerm (Classical.choose h) else 1

/-- Equal or adjacent. -/
def R (x y : Fin flagL.nv) : Prop := x = y ∨ flagL.Adj x y

/-! ### The labels -/

theorem tau_edge (a : Fin flagL.m) : tau (flagL.src a) (flagL.tgt a) = flagPerm a := by
  have h : flagL.Adj (flagL.src a) (flagL.tgt a) := ⟨a, rfl, rfl⟩
  rw [tau, dif_pos h]
  obtain ⟨h1, h2⟩ := Classical.choose_spec h
  rw [flagL_edge_unique _ _ h1 h2]

theorem tau_self (x : Fin flagL.nv) : tau x x = 1 := by
  rw [tau, dif_neg (flagL_isGraph.irrefl x)]

theorem flagPerm_rev' (a : Fin flagL.m) : flagPerm (flagL.rev a) = (flagPerm a)⁻¹ :=
  eq_inv_of_mul_eq_one_right (flagPerm_rev a)

theorem tau_mul_tau_symm {x y : Fin flagL.nv} (h : R x y) : tau x y * tau y x = 1 := by
  rcases h with rfl | ⟨a, rfl, rfl⟩
  · rw [tau_self, mul_one]
  · have h := tau_edge (flagL.rev a)
    rw [flagL_rev_src, flagL_rev_tgt] at h
    rw [tau_edge, h, flagPerm_rev', mul_inv_cancel]

theorem tau_tri {x y z : Fin flagL.nv} (hxy : R x y) (hyz : R y z) (hxz : R x z) :
    tau x y * tau y z = tau x z := by
  by_cases e1 : x = y
  · subst e1; rw [tau_self, one_mul]
  by_cases e2 : y = z
  · subst e2; rw [tau_self, mul_one]
  by_cases e3 : x = z
  · subst e3; rw [tau_mul_tau_symm hxy, tau_self]
  obtain ⟨a, rfl, rfl⟩ := hxy.resolve_left e1
  obtain ⟨b, hb1, rfl⟩ := hyz.resolve_left e2
  obtain ⟨c, hc1, hc2⟩ := hxz.resolve_left e3
  have hcyc := flagL_cycle_rel flagPerm flagPerm_rev' flagPerm_tri (a := a) (b := b)
    (c := flagL.rev c) hb1.symm (by rw [flagL_rev_src, hc2]) (by rw [flagL_rev_tgt, hc1])
  rw [tau_edge, ← hb1, tau_edge, ← hc1, ← hc2, tau_edge]
  rw [flagPerm_rev'] at hcyc
  calc flagPerm a * flagPerm b = flagPerm a * flagPerm b * (flagPerm c)⁻¹ * flagPerm c := by
        group
    _ = flagPerm c := by rw [hcyc, one_mul]

/-! ### Cliques and last letters -/

/-- A clique. -/
def IsCl (K : Finset (Fin flagL.nv)) : Prop := ∀ u ∈ K, ∀ v ∈ K, u = v ∨ flagL.Adj u v

/-- The subgroup generated by the vertices of `K`. -/
noncomputable abbrev clSub (K : Finset (Fin flagL.nv)) : Subgroup (Equiv.Perm PosL) :=
  Subgroup.closure (gen flagL_isGraph '' (K : Set (Fin flagL.nv)))

theorem g_mem {K : Finset (Fin flagL.nv)} {v : Fin flagL.nv} (hv : v ∈ K) : g v ∈ clSub K :=
  subset_closure ⟨v, hv, rfl⟩

theorem R_of_mem {K : Finset (Fin flagL.nv)} (hK : IsCl K) {h₁ h₂ : Equiv.Perm PosL}
    (hh₁ : h₁ ∈ clSub K) (hh₂ : h₂ ∈ clSub K) (p : PosL) {s t : Fin flagL.nv}
    (hs : s ∈ Ivert flagL.Adj (h₁ p).1) (ht : t ∈ Ivert flagL.Adj (h₂ p).1) : R s t :=
  ivert_adj_of_rest_eq hK
    (by rw [rest_of_mem_closure flagL_isGraph hh₁, rest_of_mem_closure flagL_isGraph hh₂]) hs ht

theorem cv_mem {p : PosL} (hp : height p.1 ≠ 0) : cv p ∈ Ivert flagL.Adj p.1 := by
  have h := ivert_nonempty p.2 hp
  rw [cv, dif_pos h]
  exact h.some_mem

theorem cv_R {K : Finset (Fin flagL.nv)} (hK : IsCl K) {h₁ h₂ : Equiv.Perm PosL}
    (hh₁ : h₁ ∈ clSub K) (hh₂ : h₂ ∈ clSub K) {p : PosL} (hp₁ : height (h₁ p).1 ≠ 0)
    (hp₂ : height (h₂ p).1 ≠ 0) : R (cv (h₁ p)) (cv (h₂ p)) :=
  R_of_mem hK hh₁ hh₂ p (cv_mem hp₁) (cv_mem hp₂)

/-- The two endpoints of an edge form a clique. -/
theorem isCl_edge (a : Fin flagL.m) : IsCl {flagL.src a, flagL.tgt a} := by
  have h1 : flagL.Adj (flagL.src a) (flagL.tgt a) := ⟨a, rfl, rfl⟩
  have h2 := flagL_isGraph.symm _ _ h1
  intro u hu v hv
  simp only [Finset.mem_insert, Finset.mem_singleton] at hu hv
  rcases hu with rfl | rfl <;> rcases hv with rfl | rfl <;> simp_all

theorem g_commute {u v : Fin flagL.nv} (h : flagL.Adj u v) : Commute (g u) (g v) :=
  gen_commute flagL_isGraph h

theorem height_g_zpow (v : Fin flagL.nv) (k : ℤ) (p : PosL) :
    height ((g v ^ k) p).1 = height p.1 + k :=
  height_gen_zpow flagL_isGraph v k p

theorem height_beta (a : Fin flagL.m) (p : PosL) : height (beta a p).1 = height p.1 := by
  rw [beta, Equiv.Perm.mul_apply, height_gen, height_gen_inv]; ring

theorem beta_mem {K : Finset (Fin flagL.nv)} {a : Fin flagL.m} (hs : flagL.src a ∈ K)
    (ht : flagL.tgt a ∈ K) : beta a ∈ clSub K :=
  mul_mem (g_mem hs) (inv_mem (g_mem ht))

theorem beta_rev (a : Fin flagL.m) : beta (flagL.rev a) = (beta a)⁻¹ := by
  rw [beta, beta, flagL_rev_src, flagL_rev_tgt, mul_inv_rev, inv_inv]

theorem height_prod_beta (es : List (Fin flagL.m)) (p : PosL) :
    height ((es.map beta).prod p).1 = height p.1 := by
  induction es with
  | nil => rfl
  | cons e es ih => rw [List.map_cons, List.prod_cons, Equiv.Perm.mul_apply, height_beta, ih]

theorem prod_beta_mem {K : Finset (Fin flagL.nv)} {es : List (Fin flagL.m)}
    (hes : ∀ e ∈ es, flagL.src e ∈ K ∧ flagL.tgt e ∈ K) : (es.map beta).prod ∈ clSub K := by
  apply list_prod_mem
  intro x hx
  obtain ⟨e, he, rfl⟩ := List.mem_map.1 hx
  exact beta_mem (hes e he).1 (hes e he).2

/-! ### The fibre action -/

variable (n : ℤ)

/-- Omega. -/
abbrev Om := PosL × Fin 5

/-- The fibre transport of the edge `a` at the position `p` (trivial off height `n`). -/
noncomputable def kappa (a : Fin flagL.m) (p : PosL) : Equiv.Perm (Fin 5) :=
  if height p.1 = n then tau (cv (beta a p)) (cv p) else 1

/-- The action of an edge. -/
noncomputable def F (a : Fin flagL.m) (x : Om) : Om := (beta a x.1, kappa n a x.1 x.2)

variable {n}

theorem F_F_rev (hn : n ≠ 0) (a : Fin flagL.m) (x : Om) : F n a (F n (flagL.rev a) x) = x := by
  obtain ⟨p, f⟩ := x
  simp only [F]
  have hb : beta a (beta (flagL.rev a) p) = p := by
    rw [beta_rev]; exact Equiv.apply_symm_apply _ _
  refine Prod.ext hb ?_
  simp only [kappa, hb, height_beta]
  split_ifs with h
  · have hR : R (cv p) (cv (beta (flagL.rev a) p)) := by
      have := cv_R (isCl_edge a) (one_mem _) (beta_mem (K := {flagL.src a, flagL.tgt a})
        (a := flagL.rev a) (by simp [flagL_rev_src]) (by simp [flagL_rev_tgt])) (p := p)
        (by simpa [h] using hn) (by rw [height_beta, h]; exact hn)
      simpa using this
    change (tau (cv p) (cv (beta (flagL.rev a) p)) * tau (cv (beta (flagL.rev a) p)) (cv p)) f = f
    rw [tau_mul_tau_symm hR]; rfl
  · rfl

/-- The permutation of an edge. -/
noncomputable def Fperm (hn : n ≠ 0) (a : Fin flagL.m) : Equiv.Perm Om where
  toFun := F n a
  invFun := F n (flagL.rev a)
  left_inv x := by
    have := F_F_rev hn (flagL.rev a) x
    rwa [flagL_rev_rev] at this
  right_inv x := F_F_rev hn a x

theorem Fperm_apply (hn : n ≠ 0) (a : Fin flagL.m) (x : Om) : Fperm hn a x = F n a x := rfl

theorem Fperm_rev (hn : n ≠ 0) (a : Fin flagL.m) : Fperm hn (flagL.rev a) = (Fperm hn a)⁻¹ := by
  rw [eq_inv_iff_mul_eq_one]
  refine Equiv.ext fun x => ?_
  rw [Equiv.Perm.mul_apply, Fperm_apply, Fperm_apply]
  have := F_F_rev hn (flagL.rev a) x
  rwa [flagL_rev_rev] at this

/-- **Telescoping** along a list of edges inside a clique. -/
theorem prod_Fperm (hn : n ≠ 0) {K : Finset (Fin flagL.nv)} (hK : IsCl K) :
    ∀ {es : List (Fin flagL.m)}, (∀ e ∈ es, flagL.src e ∈ K ∧ flagL.tgt e ∈ K) →
      ∀ (p : PosL) (f : Fin 5), (es.map (Fperm hn)).prod (p, f) =
        ((es.map beta).prod p,
          (if height p.1 = n then tau (cv ((es.map beta).prod p)) (cv p) else 1) f)
  | [], _, p, f => by
    simp [tau_self]
  | e :: es, hes, p, f => by
    have ih := prod_Fperm hn hK (es := es) (fun e' he' => hes e' (by simp [he'])) p f
    rw [List.map_cons, List.prod_cons, Equiv.Perm.mul_apply, ih, Fperm_apply, F]
    simp only [List.map_cons, List.prod_cons, Equiv.Perm.mul_apply]
    refine Prod.ext rfl ?_
    simp only [kappa, height_prod_beta]
    split_ifs with h
    · have hn' : height p.1 ≠ 0 := by rw [h]; exact hn
      have hQ := prod_beta_mem (K := K) (es := es) (fun e' he' => hes e' (by simp [he']))
      have he := beta_mem (hes e (by simp)).1 (hes e (by simp)).2
      have h1 : height ((beta e * (es.map beta).prod) p).1 ≠ 0 := by
        rw [Equiv.Perm.mul_apply, height_beta, height_prod_beta]; exact hn'
      have h2 : height (((es.map beta).prod) p).1 ≠ 0 := by rw [height_prod_beta]; exact hn'
      have h3 : height ((1 : Equiv.Perm PosL) p).1 ≠ 0 := hn'
      have r12 := cv_R hK (mul_mem he hQ) hQ h1 h2
      have r23 := cv_R hK hQ (one_mem _) h2 h3
      have r13 := cv_R hK (mul_mem he hQ) (one_mem _) h1 h3
      simp only [Equiv.Perm.mul_apply, Equiv.Perm.one_apply] at r12 r23 r13
      rw [← tau_tri r12 r23 r13]
      rfl
    · rfl

theorem prod_Fperm_eq_one (hn : n ≠ 0) {K : Finset (Fin flagL.nv)} (hK : IsCl K)
    {es : List (Fin flagL.m)} (hes : ∀ e ∈ es, flagL.src e ∈ K ∧ flagL.tgt e ∈ K)
    (h1 : (es.map beta).prod = 1) : (es.map (Fperm hn)).prod = 1 := by
  refine Equiv.ext fun x => ?_
  obtain ⟨p, f⟩ := x
  rw [prod_Fperm hn hK hes, h1]
  simp [tau_self]

/-! ### The homomorphism -/

theorem isCl_tri {t : Fin flagL.m × Fin flagL.m × Fin flagL.m} (ht : t ∈ flagL.tri) :
    IsCl {flagL.src t.1, flagL.src t.2.1, flagL.src t.2.2} := by
  have a1 : flagL.Adj (flagL.src t.1) (flagL.src t.2.1) := ⟨t.1, rfl, flagL_tri_ab t ht⟩
  have a2 : flagL.Adj (flagL.src t.2.1) (flagL.src t.2.2) := ⟨t.2.1, rfl, flagL_tri_bc t ht⟩
  have a3 : flagL.Adj (flagL.src t.2.2) (flagL.src t.1) := ⟨t.2.2, rfl, flagL_tri_ca t ht⟩
  have b1 := flagL_isGraph.symm _ _ a1
  have b2 := flagL_isGraph.symm _ _ a2
  have b3 := flagL_isGraph.symm _ _ a3
  intro u hu v hv
  simp only [Finset.mem_insert, Finset.mem_singleton] at hu hv
  rcases hu with rfl | rfl | rfl <;> rcases hv with rfl | rfl | rfl <;> simp_all

theorem tri_edges_mem {t : Fin flagL.m × Fin flagL.m × Fin flagL.m} (ht : t ∈ flagL.tri) :
    ∀ e ∈ [t.1, t.2.1, t.2.2], flagL.src e ∈ ({flagL.src t.1, flagL.src t.2.1, flagL.src t.2.2} :
      Finset (Fin flagL.nv)) ∧ flagL.tgt e ∈ ({flagL.src t.1, flagL.src t.2.1, flagL.src t.2.2} :
      Finset (Fin flagL.nv)) := by
  intro e he
  simp only [List.mem_cons, List.not_mem_nil, or_false] at he
  rcases he with rfl | rfl | rfl
  · simp [flagL_tri_ab t ht]
  · simp [flagL_tri_bc t ht]
  · simp [flagL_tri_ca t ht]

theorem beta_tri {t : Fin flagL.m × Fin flagL.m × Fin flagL.m} (ht : t ∈ flagL.tri) :
    ([t.1, t.2.1, t.2.2].map beta).prod = 1 := by
  simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one, beta,
    flagL_tri_ab t ht, flagL_tri_bc t ht, flagL_tri_ca t ht]
  group

theorem beta_tri_rev {t : Fin flagL.m × Fin flagL.m × Fin flagL.m} (ht : t ∈ flagL.tri) :
    ([t.2.2, t.2.1, t.1].map beta).prod = 1 := by
  simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one, beta,
    flagL_tri_ab t ht, flagL_tri_bc t ht, flagL_tri_ca t ht]
  set x := g (flagL.src t.1)
  set y := g (flagL.src t.2.1)
  set z := g (flagL.src t.2.2)
  have hxy : Commute x y := g_commute ⟨t.1, rfl, flagL_tri_ab t ht⟩
  have hyz : Commute y z := g_commute ⟨t.2.1, rfl, flagL_tri_bc t ht⟩
  have hzx : Commute z x := g_commute ⟨t.2.2, rfl, flagL_tri_ca t ht⟩
  have e1 : x⁻¹ * y = y * x⁻¹ := hxy.inv_left.eq
  have e2 : x⁻¹ * z⁻¹ = z⁻¹ * x⁻¹ := hzx.symm.inv_inv.eq
  have e3 : y * z⁻¹ = z⁻¹ * y := hyz.inv_right.eq
  calc z * x⁻¹ * (y * z⁻¹ * (x * y⁻¹)) = z * (x⁻¹ * y) * z⁻¹ * x * y⁻¹ := by group
    _ = z * y * (x⁻¹ * z⁻¹) * x * y⁻¹ := by rw [e1]; group
    _ = z * (y * z⁻¹) * y⁻¹ := by rw [e2]; group
    _ = 1 := by rw [e3]; group

/-- **The homomorphism `ψ n : P → Perm Ω`.** -/
noncomputable def psi (hn : n ≠ 0) : flagL.PGrp →* Equiv.Perm Om :=
  PresentedGroup.toGroup (f := Fperm hn) (fun r hr => by
    rcases hr with (⟨a, rfl⟩ | ⟨t, ht, rfl⟩) | ⟨t, ht, rfl⟩
    · simp only [map_mul, FreeGroup.lift_apply_of, Fperm_rev, mul_inv_cancel]
    · have := prod_Fperm_eq_one hn (isCl_tri ht) (tri_edges_mem ht) (beta_tri ht)
      simpa [mul_assoc] using this
    · have hes : ∀ e ∈ [t.2.2, t.2.1, t.1], flagL.src e ∈
          ({flagL.src t.1, flagL.src t.2.1, flagL.src t.2.2} : Finset (Fin flagL.nv)) ∧
          flagL.tgt e ∈ ({flagL.src t.1, flagL.src t.2.1, flagL.src t.2.2} :
            Finset (Fin flagL.nv)) := fun e he =>
        tri_edges_mem ht e (by simp only [List.mem_cons, List.not_mem_nil] at he ⊢; tauto)
      have := prod_Fperm_eq_one hn (isCl_tri ht) hes (beta_tri_rev ht)
      simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one] at this
      simp only [map_mul, map_inv, FreeGroup.lift_apply_of]
      rw [← mul_inv_rev, ← mul_inv_rev, this, inv_one])

theorem psi_xP (hn : n ≠ 0) (a : Fin flagL.m) : psi hn (flagL.xP a) = Fperm hn a :=
  PresentedGroup.toGroup.of _

/-! ### Powered loops -/

theorem psi_powVal (hn : n ≠ 0) (m : ℤ) (w : List (Fin flagL.m)) :
    psi hn (flagL.powVal m w) = (w.map fun e => Fperm hn e ^ m).prod := by
  simp only [powVal, map_list_prod, List.map_map]
  congr 1
  apply List.map_congr_left
  intro e _
  simp [psi_xP]

theorem edge_mem_K (e : Fin flagL.m) :
    ∀ a ∈ ({e} : Set (Fin flagL.m)) ∪ {flagL.rev e}, flagL.src a ∈
      ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) ∧
      flagL.tgt a ∈ ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) := by
  rintro a (rfl | rfl)
  · simp
  · simp [flagL_rev_src, flagL_rev_tgt]

/-- One powered edge. -/
theorem Fperm_zpow (hn : n ≠ 0) (e : Fin flagL.m) (k : ℤ) (p : PosL) (f : Fin 5) :
    (Fperm hn e ^ k) (p, f) = ((beta e ^ k) p,
      (if height p.1 = n then tau (cv ((beta e ^ k) p)) (cv p) else 1) f) := by
  have hK := isCl_edge e
  obtain ⟨j, rfl | rfl⟩ := Int.eq_nat_or_neg k
  · have hes : ∀ a ∈ List.replicate j e, flagL.src a ∈
        ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) ∧
        flagL.tgt a ∈ ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) := by
      intro a ha
      rw [List.eq_of_mem_replicate ha]
      simp
    have h := prod_Fperm hn hK hes p f
    rw [List.map_replicate, List.prod_replicate, List.map_replicate, List.prod_replicate] at h
    simpa only [zpow_natCast] using h
  · have hes : ∀ a ∈ List.replicate j (flagL.rev e), flagL.src a ∈
        ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) ∧
        flagL.tgt a ∈ ({flagL.src e, flagL.tgt e} : Finset (Fin flagL.nv)) := by
      intro a ha
      rw [List.eq_of_mem_replicate ha]
      simp [flagL_rev_src, flagL_rev_tgt]
    have h := prod_Fperm hn hK hes p f
    rw [List.map_replicate, List.prod_replicate, List.map_replicate, List.prod_replicate,
      Fperm_rev, beta_rev] at h
    simpa only [zpow_neg, zpow_natCast, inv_pow] using h

theorem beta_zpow_mul (e : Fin flagL.m) (m : ℤ) :
    beta e ^ m * g (flagL.tgt e) ^ m = g (flagL.src e) ^ m := by
  have hc : Commute (g (flagL.src e)) (g (flagL.tgt e))⁻¹ :=
    (g_commute ⟨e, rfl, rfl⟩).inv_right
  rw [beta, hc.mul_zpow, inv_zpow, inv_mul_cancel_right]

theorem isCl_single (v : Fin flagL.nv) : IsCl {v} := by
  intro u hu w hw
  simp only [Finset.mem_singleton] at hu hw
  exact Or.inl (hu.trans hw.symm)

/-- **The cone lemma** for a powered walk. -/
theorem walk_cone (hn : n ≠ 0) (m : ℤ) : ∀ (x : Fin flagL.nv) (w : List (Fin flagL.m))
    (y : Fin flagL.nv), IsWalk flagL x w y → ∀ (z : PosL) (r : Fin flagL.nv),
    (height ((g y ^ m) z).1 = n → r ∈ Ivert flagL.Adj z.1) → ∀ f : Fin 5,
    (w.map fun e => Fperm hn e ^ m).prod ((g y ^ m) z, f) = ((g x ^ m) z,
      (if height ((g y ^ m) z).1 = n then tau (cv ((g x ^ m) z)) r * tau r (cv ((g y ^ m) z))
        else 1) f)
  | x, [], y, h, z, r, hr, f => by
    change x = y at h
    subst h
    simp only [List.map_nil, List.prod_nil, Equiv.Perm.one_apply]
    split_ifs with hh
    · have hq : height ((g x ^ m) z).1 ≠ 0 := by rw [hh]; exact hn
      have hR : R (cv ((g x ^ m) z)) r := by
        have := R_of_mem (isCl_single x) (zpow_mem (g_mem (Finset.mem_singleton_self x)) m)
          (one_mem _) z (cv_mem hq) (hr hh)
        simpa using this
      rw [tau_mul_tau_symm hR]; rfl
    · rfl
  | x, e :: w, y, h, z, r, hr, f => by
    obtain ⟨hx, hw⟩ := h
    subst hx
    have ih := walk_cone hn m (flagL.tgt e) w y hw z r hr f
    rw [List.map_cons, List.prod_cons, Equiv.Perm.mul_apply, ih, Fperm_zpow,
      ← Equiv.Perm.mul_apply, beta_zpow_mul]
    refine Prod.ext rfl ?_
    have hh : height ((g (flagL.tgt e) ^ m) z).1 = height ((g y ^ m) z).1 := by
      rw [height_g_zpow, height_g_zpow]
    simp only [hh]
    split_ifs with h1
    · have hq : ∀ v, height ((g v ^ m) z).1 ≠ 0 := by
        intro v; rw [height_g_zpow, ← height_g_zpow y, h1]; exact hn
      have hK := isCl_edge e
      have m1 := zpow_mem (g_mem (K := {flagL.src e, flagL.tgt e})
        (Finset.mem_insert_self _ _)) m
      have m2 := zpow_mem (g_mem (K := {flagL.src e, flagL.tgt e})
        (Finset.mem_insert_of_mem (Finset.mem_singleton_self _))) m
      have r12 := cv_R hK m1 m2 (hq _) (hq _)
      have r2r : R (cv ((g (flagL.tgt e) ^ m) z)) r := by
        simpa using R_of_mem hK m2 (one_mem _) z (cv_mem (hq _)) (hr h1)
      have r1r : R (cv ((g (flagL.src e) ^ m) z)) r := by
        simpa using R_of_mem hK m1 (one_mem _) z (cv_mem (hq _)) (hr h1)
      rw [← tau_tri r12 r2r r1r]
      simp only [Equiv.Perm.mul_apply]
    · rfl

theorem height_emptyPos : height (emptyPos flagL.Adj).1 = 0 := height_proj_nil

theorem cv_base (hn : n ≠ 0) (v : Fin flagL.nv) : cv ((g v ^ n) (emptyPos flagL.Adj)) = v := by
  have hh : height ((g v ^ n) (emptyPos flagL.Adj)).1 ≠ 0 := by
    rw [height_g_zpow, height_emptyPos, zero_add]; exact hn
  have hrest : rest {v} ((g v ^ n) (emptyPos flagL.Adj)).1 = fun _ _ => [] := by
    rw [rest_of_mem_closure flagL_isGraph (zpow_mem (g_mem (Finset.mem_singleton_self v)) n)]
    exact rest_proj_nil _
  exact ivert_subset_of_rest_nil hrest (cv_mem hh)

/-- The `n`-th powered walk based at the identity carries the `S₅`-image of the walk. -/
theorem walk_base (hn : n ≠ 0) : ∀ (x : Fin flagL.nv) (w : List (Fin flagL.m))
    (y : Fin flagL.nv), IsWalk flagL x w y → ∀ f : Fin 5,
    (w.map fun e => Fperm hn e ^ n).prod ((g y ^ n) (emptyPos flagL.Adj), f) =
      ((g x ^ n) (emptyPos flagL.Adj), (w.map flagPerm).prod f)
  | x, [], y, h, f => by
    change x = y at h
    subst h
    simp
  | x, e :: w, y, h, f => by
    obtain ⟨hx, hw⟩ := h
    subst hx
    have ih := walk_base hn (flagL.tgt e) w y hw f
    rw [List.map_cons, List.prod_cons, Equiv.Perm.mul_apply, ih, Fperm_zpow,
      ← Equiv.Perm.mul_apply, beta_zpow_mul]
    refine Prod.ext rfl ?_
    have hh : height ((g (flagL.tgt e) ^ n) (emptyPos flagL.Adj)).1 = n := by
      rw [height_g_zpow, height_emptyPos, zero_add]
    simp only [hh, if_true, cv_base hn, tau_edge, List.map_cons, List.prod_cons,
      Equiv.Perm.mul_apply]

/-- **`ψ n` kills `ρ_m` for every `m ≠ n`.** -/
theorem psi_comp_rho (hn : n ≠ 0) {m : ℤ} (hm : m ≠ n) :
    (psi hn).comp (rho flagL_wf m) = 1 := by
  apply PresentedGroup.ext
  intro e
  rw [MonoidHom.comp_apply, rho_of, MonoidHom.one_apply, ← mkP_fundCycle, mkP_loopPow,
    psi_powVal]
  have hw := isWalk_fundCycle flagL_wf flagL_connected e
  refine Equiv.ext fun x => ?_
  obtain ⟨p, f⟩ := x
  set z := (g flagL.root ^ m)⁻¹ p with hzdef
  have hz : (g flagL.root ^ m) z = p := by simp [z]
  by_cases hp : height p.1 = n
  · have hz0 : height z.1 ≠ 0 := by
      have := height_g_zpow flagL.root m z
      rw [hz, hp] at this
      intro h0; rw [h0] at this; exact hm (by linarith)
    obtain ⟨r, hr⟩ := ivert_nonempty z.2 hz0
    have h := walk_cone hn m _ _ _ hw z r (fun _ => hr) f
    rw [hz, if_pos hp] at h
    rw [h, Equiv.Perm.one_apply]
    have hq : height p.1 ≠ 0 := by rw [hp]; exact hn
    have hR : R (cv p) r := by
      have := R_of_mem (isCl_single flagL.root)
        (zpow_mem (g_mem (Finset.mem_singleton_self flagL.root)) m) (one_mem _) z
        (by rw [hz]; exact cv_mem hq) hr
      simpa [hz] using this
    rw [tau_mul_tau_symm hR]; rfl
  · have h := walk_cone hn m _ _ _ hw z flagL.root (fun h => absurd (hz ▸ h) hp) f
    rw [hz, if_neg hp] at h
    rw [h]; rfl

theorem flagLoop_perm_ne_one : (flagLoopL.map flagPerm).prod ≠ 1 := by
  intro h1
  revert h1
  decide +kernel

/-- **`ψ n` detects the `n`-th powered loop.** -/
theorem psi_rho_loop_ne_one (hn : n ≠ 0) : psi hn (rho flagL_wf n (piVal flagLoopL)) ≠ 1 := by
  rw [rho_loop flagL_wf n _ flagLoop_isWalk, psi_powVal]
  intro h
  apply flagLoop_perm_ne_one
  refine Equiv.ext fun f => ?_
  have := walk_base hn _ _ _ flagLoop_isWalk f
  rw [h, Equiv.Perm.one_apply, Prod.mk.injEq] at this
  exact this.2.symm

end TheoremA.Leary.Detection

namespace TheoremA.Leary

open Detection EdgeData

/-- **Separation (SEP) for `flagL`, proved.**  For every `S ⊆ ℤ` and every integer `n ≠ 0` with
`n ∉ S`, `ρₙ([γ]) ∉ N_S`. -/
theorem flagSeparation : FlagSeparation := by
  intro S n hn hnS hmem
  apply psi_rho_loop_ne_one hn
  have hle : NS flagL_wf S ≤ (psi hn).ker := by
    unfold NS
    apply Subgroup.normalClosure_le_normal
    intro x hx
    simp only [Set.mem_iUnion, Set.mem_range] at hx
    obtain ⟨m, hm, y, rfl⟩ := hx
    have hmn : m ≠ n := fun h => hnS (h ▸ hm)
    rw [SetLike.mem_coe, MonoidHom.mem_ker, ← MonoidHom.comp_apply, psi_comp_rho hn hmn,
      MonoidHom.one_apply]
  exact hle hmem

/-- **Leary's detection theorem for `flagL`, proved** (in the directed-edge presentation). -/
theorem learyDetectionFlag : LearyDetectionFlag :=
  learyDetection_of_flagSeparation flagSeparation

end TheoremA.Leary
