module

public import RequestProject.TheoremA.Leary.Package
public import RequestProject.TheoremA.Leary.Flagness

/-!
# The published-source boundary: Leary's directed-edge presentation and `FlagSeparation`

This file compares the project's presentation `J(S)` over the fixed flag complex `flagL` with the
directed-edge presentation of Leary's group `G_L(S)` (I. J. Leary, *Uncountably many groups of
type FP*, Section 14):

* generators: all directed edges of `L`;
* relators `a · ā` for every directed edge `a` (`ā = rev a` the reversed edge);
* relators `a b c` and `a⁻¹ b⁻¹ c⁻¹` for every **directed triangle** `(a, b, c)`, i.e. every
  directed 3-cycle of edges whose vertex set is a 2-simplex of `L` (`IsDirTri`);
* relators `a₁ⁿ ⋯ a_lⁿ` for every `n ∈ S` and every closed directed edge loop `(a₁, …, a_l)`,
  based at **any** vertex (for `n = 0` these relators are trivial words).

Main results.
* `nc_learyRels_eq` — for `flagL`, the normal closures of Leary's relators and of the project's
  relators `jRels` (short relators, and powered fundamental cycles of the spanning tree only)
  coincide in the free group on the directed edges.  Hence `learyEquivJ S` is an isomorphism of
  Leary's presented group with `J(S)` which is the identity on directed-edge generators
  (`learyEquivJ_of`) and matches the distinguished powered loop (`learyEquivJ_loopPow`).
* `LearyDetectionFlag` — the presentation-language form of Leary's detection theorem for `flagL`
  and the distinguished loop: for every `S ⊆ ℤ` with `0 ∈ S` and every `n : ℤ`, the word
  `a₁ⁿ a₂ⁿ a₃ⁿ a₄ⁿ` is trivial in Leary's presented group iff `n ∈ S`.
* `learyDetection_iff_flagSeparation` — this proposition is **equivalent** to the project's
  `FlagSeparation` (in particular `flagSeparation_of_learyDetection`).
* Edge-path homotopy: `EdgeHomotopic` (generated by inserting/removing a backtrack `a ā` and by
  replacing an edge `c̄` by `a b` across a directed triangle `(a, b, c)`), `piVal_eq_of_homotopic`
  (the tree presentation value is a homotopy invariant), and
  `flagLoop_not_homotopic_nil` — the distinguished loop is **not** edge-path null-homotopic in
  `flagL` (transported from `flagLoop_ne_one`).  The converse comparison (that the tree
  presentation `Π_L` is isomorphic to the full combinatorial edge-path group) is not formalized
  and is not needed for the equivalence above.
-/

@[expose] public section

namespace TheoremA.Leary

open Subgroup EdgeData TheoremA.RelPres TheoremA.Coding

namespace EdgeData

variable (D : EdgeData)

/-- A **directed triangle**: a directed 3-cycle of edges whose vertex set is a 2-simplex. -/
def IsDirTri (a b c : Fin D.m) : Prop :=
  D.tgt a = D.src b ∧ D.tgt b = D.src c ∧ D.tgt c = D.src a ∧
    ∃ t ∈ D.tri, D.triVerts t = {D.src a, D.src b, D.src c}

/-- Relators of Leary's directed-edge presentation of `G_L(S)`. -/
def learyRels (S : Set ℤ) : Set (FreeGroup (Fin D.m)) :=
  {r | ∃ a, r = D.fe a * D.fe (D.rev a)} ∪
  {r | ∃ a b c, D.IsDirTri a b c ∧ r = D.fe a * D.fe b * D.fe c} ∪
  {r | ∃ a b c, D.IsDirTri a b c ∧ r = (D.fe a)⁻¹ * (D.fe b)⁻¹ * (D.fe c)⁻¹} ∪
  {r | ∃ n ∈ S, ∃ v w, IsWalk D v w v ∧ r = D.loopPow w n}

/-- Leary's presented group `G_L(S)`. -/
abbrev LearyGrp (S : Set ℤ) := PresentedGroup (D.learyRels S)

variable {D}

theorem isWalk_append : ∀ {u : Fin D.nv} {w : List (Fin D.m)} {v x : Fin D.nv}
    {w' : List (Fin D.m)}, IsWalk D u w v → IsWalk D v w' x → IsWalk D u (w ++ w') x
  | u, [], v, x, w', h, h' => by
    change u = v at h; subst h; exact h'
  | u, a :: w, v, x, w', h, h' => ⟨h.1, isWalk_append h.2 h'⟩

theorem isWalk_revPath (hD : D.WF) : ∀ {u : Fin D.nv} {w : List (Fin D.m)} {v : Fin D.nv},
    IsWalk D u w v → IsWalk D v (D.revPath w) u
  | u, [], v, h => by change u = v at h; subst h; exact rfl
  | u, a :: w, v, h => by
    have ih := isWalk_revPath hD h.2
    have e : D.revPath (a :: w) = D.revPath w ++ [D.rev a] := by simp [revPath]
    rw [e]
    refine isWalk_append ih ⟨hD.rev_src a, ?_⟩
    change D.tgt (D.rev a) = u
    rw [hD.rev_tgt, h.1]

theorem isWalk_fundCycle (hD : D.WF) (hconn : ∀ v, IsWalk D D.root (D.path v) v) (a : Fin D.m) :
    IsWalk D D.root (D.fundCycle a) D.root :=
  isWalk_append (isWalk_append (hconn _) ⟨rfl, rfl⟩) (isWalk_revPath hD (hconn _))

/-- `N_S` is monotone in `S`. -/
theorem NS_mono (hD : D.WF) {S S' : Set ℤ} (h : S ⊆ S') : NS hD S ≤ NS hD S' :=
  normalClosure_mono (Set.biUnion_subset_biUnion_left h)

/-- Membership in the relator normal closure of `J(S)` is membership of the image in `N_S`. -/
theorem mem_nc_jRels_iff (hD : D.WF) (S : Set ℤ) (r : FreeGroup (Fin D.m)) :
    r ∈ normalClosure (D.jRels S) ↔ D.mkP r ∈ NS hD S := by
  rw [← map_normalClosure_jRels hD S]
  refine ⟨fun h => ⟨r, h, rfl⟩, ?_⟩
  rintro ⟨r', hr', he⟩
  have h1 : D.mkP (r'⁻¹ * r) = 1 := by rw [map_mul, map_inv, he, inv_mul_cancel]
  have h2 : r'⁻¹ * r ∈ normalClosure (D.jRels S) :=
    normalClosure_mono Set.subset_union_left ((QuotientGroup.eq_one_iff _).1 h1)
  simpa using mul_mem hr' h2

/-- Powered closed walks based anywhere have image in `N_S`. -/
theorem powVal_mem_NS (hD : D.WF) {S : Set ℤ} {n : ℤ} (hn : n ∈ S) {v : Fin D.nv}
    {w : List (Fin D.m)} (hw : IsWalk D v w v) : D.powVal n w ∈ NS hD S := by
  have h := rho_walk hD n v w v hw
  have hmem : rho hD n (piVal w) ∈ NS hD S :=
    subset_normalClosure (Set.mem_biUnion hn ⟨_, rfl⟩)
  rw [h] at hmem
  have := (NS_normal hD S).conj_mem _ hmem (D.gP n v)⁻¹
  simpa [mul_assoc] using this

end EdgeData

/-! ### Directed 3-cycles of `flagL` -/

/-- Reversal on edge indices. -/
def revN (a : Nat) : Nat := if a % 2 = 0 then a + 1 else a - 1

/-- `(a, b, c)` is a rotation of the triangle `t` or of its reversal. -/
def formB (t : Nat × Nat × Nat) (a b c : Nat) : Bool :=
  (a == t.1 && b == t.2.1 && c == t.2.2) || (a == t.2.1 && b == t.2.2 && c == t.1) ||
  (a == t.2.2 && b == t.1 && c == t.2.1) ||
  (a == revN t.2.2 && b == revN t.2.1 && c == revN t.1) ||
  (a == revN t.2.1 && b == revN t.1 && c == revN t.2.2) ||
  (a == revN t.1 && b == revN t.2.2 && c == revN t.2.1)

/-- Every directed 3-cycle of `flagL` is a rotation of a listed triangle or of its reversal. -/
def cycFormB : Bool :=
  (List.range 432).all fun a => (outN (tgtN a)).all fun b => (outN (tgtN b)).all fun c =>
    !(tgtN c == srcN a) || flagTri.any fun t => formB t a b c

theorem cycFormB_eq : cycFormB = true := by decide +kernel

theorem revN_lt {a : Nat} (ha : a < 432) : revN a < 432 := by
  unfold revN; split_ifs <;> omega

theorem rev_val (a : Fin flagL.m) : (flagL.rev a).val = revN a.val := by
  show (Fin.ofNat 432 (if a.val % 2 = 0 then a.val + 1 else a.val - 1)).val = _
  rw [Fin.val_ofNat]; exact Nat.mod_eq_of_lt (revN_lt a.isLt)

theorem flagL_cycle_form (a b c : Fin flagL.m) (hab : flagL.tgt a = flagL.src b)
    (hbc : flagL.tgt b = flagL.src c) (hca : flagL.tgt c = flagL.src a) :
    ∃ t ∈ flagL.tri, (a = t.1 ∧ b = t.2.1 ∧ c = t.2.2) ∨ (a = t.2.1 ∧ b = t.2.2 ∧ c = t.1) ∨
      (a = t.2.2 ∧ b = t.1 ∧ c = t.2.1) ∨
      (a = flagL.rev t.2.2 ∧ b = flagL.rev t.2.1 ∧ c = flagL.rev t.1) ∨
      (a = flagL.rev t.2.1 ∧ b = flagL.rev t.1 ∧ c = flagL.rev t.2.2) ∨
      (a = flagL.rev t.1 ∧ b = flagL.rev t.2.2 ∧ c = flagL.rev t.2.1) := by
  have h := cycFormB_eq
  simp only [cycFormB, List.all_eq_true, List.mem_range, Bool.or_eq_true, Bool.not_eq_true',
    beq_eq_false_iff_ne, List.any_eq_true] at h
  have hab' := congrArg Fin.val hab; have hbc' := congrArg Fin.val hbc
  have hca' := congrArg Fin.val hca
  rw [tgt_val, src_val] at hab' hbc' hca'
  have hb : b.val ∈ outN (tgtN a.val) := by rw [hab']; exact mem_outN b
  have hc : c.val ∈ outN (tgtN b.val) := by rw [hbc']; exact mem_outN c
  rcases h a.val a.isLt b.val hb c.val hc with h' | ⟨r, hr, hp⟩
  · exact absurd hca' h'
  · have hr' : ((Fin.ofNat 432 r.1, Fin.ofNat 432 r.2.1, Fin.ofNat 432 r.2.2) :
        Fin flagL.m × Fin flagL.m × Fin flagL.m) ∈ flagL.tri := by
      simp only [flagL, List.mem_map]; exact ⟨r, hr, rfl⟩
    refine ⟨_, hr', ?_⟩
    obtain ⟨l1, l2, l3⟩ := tri_lt hr
    have v1 : (Fin.ofNat 432 r.1 : Fin flagL.m).val = r.1 := by
      rw [Fin.val_ofNat, Nat.mod_eq_of_lt l1]
    have v2 : (Fin.ofNat 432 r.2.1 : Fin flagL.m).val = r.2.1 := by
      rw [Fin.val_ofNat, Nat.mod_eq_of_lt l2]
    have v3 : (Fin.ofNat 432 r.2.2 : Fin flagL.m).val = r.2.2 := by
      rw [Fin.val_ofNat, Nat.mod_eq_of_lt l3]
    simp only [formB, Bool.or_eq_true, Bool.and_eq_true, beq_iff_eq] at hp
    rw [← v1, ← v2, ← v3, ← rev_val, ← rev_val, ← rev_val] at hp
    simp only [← Fin.ext_iff, and_assoc, or_assoc] at hp
    exact hp

/-- In any group, the relations `f ā = (f a)⁻¹` and `f t₁ f t₂ f t₃ = 1` for listed triangles
imply `f a f b f c = 1` for every directed 3-cycle `(a, b, c)` of `flagL`. -/
theorem flagL_cycle_rel {G : Type*} [Group G] (f : Fin flagL.m → G)
    (hrev : ∀ a, f (flagL.rev a) = (f a)⁻¹)
    (htri : ∀ t ∈ flagL.tri, f t.1 * f t.2.1 * f t.2.2 = 1) {a b c : Fin flagL.m}
    (hab : flagL.tgt a = flagL.src b) (hbc : flagL.tgt b = flagL.src c)
    (hca : flagL.tgt c = flagL.src a) : f a * f b * f c = 1 := by
  obtain ⟨t, ht, h⟩ := flagL_cycle_form a b c hab hbc hca
  have e := htri t ht
  set x := f t.1; set y := f t.2.1; set z := f t.2.2
  rcases h with ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩ |
    ⟨rfl, rfl, rfl⟩ | ⟨rfl, rfl, rfl⟩
  · exact e
  · calc y * z * x = x⁻¹ * (x * y * z) * x := by group
      _ = 1 := by rw [e]; group
  · calc z * x * y = (x * y)⁻¹ * (x * y * z) * (x * y) := by group
      _ = 1 := by rw [e]; group
  · rw [hrev, hrev, hrev]
    calc z⁻¹ * y⁻¹ * x⁻¹ = (x * y * z)⁻¹ := by group
      _ = 1 := by rw [e]; group
  · rw [hrev, hrev, hrev]
    calc y⁻¹ * x⁻¹ * z⁻¹ = z * (x * y * z)⁻¹ * z⁻¹ := by group
      _ = 1 := by rw [e]; group
  · rw [hrev, hrev, hrev]
    calc x⁻¹ * z⁻¹ * y⁻¹ = (y * z) * (x * y * z)⁻¹ * (y * z)⁻¹ := by group
      _ = 1 := by rw [e]; group

/-! ### Leary's presentation and `J(S)` have the same relator normal closure -/

theorem learyRels_subset (S : Set ℤ) : flagL.learyRels S ⊆ normalClosure (flagL.jRels S) := by
  rintro r (((⟨a, rfl⟩ | ⟨a, b, c, ⟨h1, h2, h3, -⟩, rfl⟩) | ⟨a, b, c, ⟨h1, h2, h3, -⟩, rfl⟩) |
    ⟨n, hn, v, w, hw, rfl⟩)
  · exact subset_normalClosure (Or.inl (Or.inl (Or.inl ⟨a, rfl⟩)))
  · rw [SetLike.mem_coe, mem_nc_jRels_iff flagL_wf]
    have : flagL.mkP (flagL.fe a * flagL.fe b * flagL.fe c) = 1 := by
      simp only [map_mul]
      exact flagL_cycle_rel flagL.xP flagL.xP_rev (fun t ht => flagL.tri_mul ht) h1 h2 h3
    rw [this]; exact one_mem _
  · rw [SetLike.mem_coe, mem_nc_jRels_iff flagL_wf]
    have : flagL.mkP ((flagL.fe a)⁻¹ * (flagL.fe b)⁻¹ * (flagL.fe c)⁻¹) = 1 := by
      simp only [map_mul, map_inv]
      exact flagL_cycle_rel (fun a => (flagL.xP a)⁻¹) (fun a => by simp only [flagL.xP_rev])
        (fun t ht => flagL.tri_mul_inv ht) h1 h2 h3
    rw [this]; exact one_mem _
  · rw [SetLike.mem_coe, mem_nc_jRels_iff flagL_wf, mkP_loopPow]
    exact powVal_mem_NS flagL_wf hn hw

theorem jRels_subset (S : Set ℤ) : flagL.jRels S ⊆ normalClosure (flagL.learyRels S) := by
  rintro r (((⟨a, rfl⟩ | ⟨t, ht, rfl⟩) | ⟨t, ht, rfl⟩) | ⟨n, hn, a, rfl⟩)
  · exact subset_normalClosure (Or.inl (Or.inl (Or.inl ⟨a, rfl⟩)))
  · exact subset_normalClosure (Or.inl (Or.inl (Or.inr ⟨_, _, _,
      ⟨flagL_tri_ab t ht, flagL_tri_bc t ht, flagL_tri_ca t ht, t, ht, rfl⟩, rfl⟩)))
  · exact subset_normalClosure (Or.inl (Or.inr ⟨_, _, _,
      ⟨flagL_tri_ab t ht, flagL_tri_bc t ht, flagL_tri_ca t ht, t, ht, rfl⟩, rfl⟩))
  · exact subset_normalClosure
      (Or.inr ⟨n, hn, _, _, isWalk_fundCycle flagL_wf flagL_connected a, rfl⟩)

/-- **Same normal closure**: Leary's directed-edge relators and the relators of `J(S)`. -/
theorem nc_learyRels_eq (S : Set ℤ) :
    normalClosure (flagL.learyRels S) = normalClosure (flagL.jRels S) :=
  le_antisymm (normalClosure_le_normal (learyRels_subset S))
    (normalClosure_le_normal (jRels_subset S))

/-- Leary's presented group `G_L(S)` is isomorphic to `J(S)`, by the identity on directed edges. -/
def learyEquivJ (S : Set ℤ) : flagL.LearyGrp S ≃* flagL.JGrp S :=
  QuotientGroup.quotientMulEquivOfEq (nc_learyRels_eq S)

theorem learyEquivJ_mk (S : Set ℤ) (r : FreeGroup (Fin flagL.m)) :
    learyEquivJ S (PresentedGroup.mk _ r) = PresentedGroup.mk _ r := rfl

theorem learyEquivJ_of (S : Set ℤ) (a : Fin flagL.m) :
    learyEquivJ S (PresentedGroup.of a) = PresentedGroup.of a := rfl

theorem mk_jRels_loopPow (S : Set ℤ) (w : List (Fin flagL.m)) (n : ℤ) :
    PresentedGroup.mk (flagL.jRels S) (flagL.loopPow w n) = (w.map fun e => flagL.xJ S e ^ n).prod := by
  simp only [loopPow, map_list_prod, List.map_map]
  rfl

/-- Compatibility on the distinguished loop: the powered loop word of Leary's group corresponds to
`Ys (jDet S) n` in `J(S)`. -/
theorem learyEquivJ_loopPow (S : Set ℤ) (n : ℤ) :
    learyEquivJ S (PresentedGroup.mk _ (flagL.loopPow flagLoopL n)) = Ys (jDet S) n := by
  rw [learyEquivJ_mk, mk_jRels_loopPow, Ys_jDet]

/-- Triviality of the powered distinguished loop in Leary's group is membership in `N_S`. -/
theorem mk_leary_loop_eq_one_iff (S : Set ℤ) (n : ℤ) :
    PresentedGroup.mk (flagL.learyRels S) (flagL.loopPow flagLoopL n) = 1 ↔
      rho flagL_wf n (piVal flagLoopL) ∈ NS flagL_wf S := by
  refine Iff.trans (QuotientGroup.eq_one_iff (N := normalClosure (flagL.learyRels S))
    (flagL.loopPow flagLoopL n)) ?_
  rw [nc_learyRels_eq, mem_nc_jRels_iff flagL_wf, mkP_loopPow,
    ← rho_loop flagL_wf n _ flagLoop_isWalk]

/-! ### The published detection statement in presentation language -/

/-- **Leary's detection for `flagL`, in presentation language.**  For every `S ⊆ ℤ` with `0 ∈ S`
and every `n : ℤ`, the powered distinguished loop `a₁ⁿ a₂ⁿ a₃ⁿ a₄ⁿ` is trivial in Leary's
directed-edge presented group `G_L(S)` if and only if `n ∈ S`. -/
def LearyDetectionFlag : Prop :=
  ∀ S : Set ℤ, (0 : ℤ) ∈ S → ∀ n : ℤ,
    PresentedGroup.mk (flagL.learyRels S) (flagL.loopPow flagLoopL n) = 1 ↔ n ∈ S

/-- The published detection statement implies the project's separation input. -/
theorem flagSeparation_of_learyDetection (h : LearyDetectionFlag) : FlagSeparation := by
  intro S n hn0 hnS hmem
  have h' := (mk_leary_loop_eq_one_iff (insert 0 S) n).2
    (NS_mono flagL_wf (Set.subset_insert _ _) hmem)
  rcases (h (insert 0 S) (Set.mem_insert _ _) n).1 h' with h1 | h1
  · exact hn0 h1
  · exact hnS h1

theorem learyDetection_of_flagSeparation (h : FlagSeparation) : LearyDetectionFlag := by
  intro S h0 n
  rw [mk_leary_loop_eq_one_iff]
  refine ⟨fun hm => ?_, fun hn => subset_normalClosure (Set.mem_biUnion hn ⟨_, rfl⟩)⟩
  by_contra hn
  exact h S n (by rintro rfl; exact hn h0) hn hm

/-- **The source boundary is exact**: Leary's detection statement for `flagL` in presentation
language is equivalent to `FlagSeparation`. -/
theorem learyDetection_iff_flagSeparation : LearyDetectionFlag ↔ FlagSeparation :=
  ⟨flagSeparation_of_learyDetection, learyDetection_of_flagSeparation⟩

/-! ### Edge-path homotopy and nontriviality of the distinguished loop -/

/-- Elementary moves of edge paths: insert a backtrack `a ā`, or replace an edge `c̄` by `a b`
across a directed triangle `(a, b, c)`. -/
inductive EdgeStep (D : EdgeData) : List (Fin D.m) → List (Fin D.m) → Prop
  | backtrack (u v : List (Fin D.m)) (a : Fin D.m) : EdgeStep D (u ++ v) (u ++ a :: D.rev a :: v)
  | triangle (u v : List (Fin D.m)) (a b c : Fin D.m) (h : D.IsDirTri a b c) :
      EdgeStep D (u ++ D.rev c :: v) (u ++ a :: b :: v)

/-- Combinatorial edge-path homotopy (equivalence closure of the elementary moves). -/
def EdgeHomotopic (D : EdgeData) : List (Fin D.m) → List (Fin D.m) → Prop :=
  Relation.EqvGen (EdgeStep D)

theorem piVal_append {D : EdgeData} (u v : List (Fin D.m)) :
    piVal (u ++ v) = piVal u * piVal v := by
  simp [piVal, List.prod_append]

theorem piVal_cons {D : EdgeData} (a : Fin D.m) (v : List (Fin D.m)) :
    piVal (a :: v) = (PresentedGroup.of a : D.PiGrp) * piVal v := by
  simp [piVal]

theorem pi_of_rev (a : Fin flagL.m) :
    (PresentedGroup.of (flagL.rev a) : flagL.PiGrp) = (PresentedGroup.of a)⁻¹ := by
  refine eq_inv_of_mul_eq_one_right ?_
  exact (QuotientGroup.eq_one_iff (N := normalClosure flagL.piRels) (flagL.fe a * flagL.fe (flagL.rev a))).2
    (subset_normalClosure (Or.inl (Or.inl ⟨a, rfl⟩)))

theorem pi_tri {t} (ht : t ∈ flagL.tri) :
    (PresentedGroup.of t.1 : flagL.PiGrp) * PresentedGroup.of t.2.1 * PresentedGroup.of t.2.2 = 1 :=
  (QuotientGroup.eq_one_iff (N := normalClosure flagL.piRels)
    (flagL.fe t.1 * flagL.fe t.2.1 * flagL.fe t.2.2)).2 (subset_normalClosure (Or.inr ⟨t, ht, rfl⟩))

theorem piVal_step_flagL {w w' : List (Fin flagL.m)} (h : EdgeStep flagL w w') :
    piVal w = piVal w' := by
  cases h with
  | backtrack u v a =>
    rw [piVal_append, piVal_append, piVal_cons, piVal_cons, pi_of_rev, mul_inv_cancel_left]
  | triangle u v a b c h =>
    obtain ⟨h1, h2, h3, -⟩ := h
    have e := flagL_cycle_rel (fun a => (PresentedGroup.of a : flagL.PiGrp)) pi_of_rev
      (fun t ht => pi_tri ht) h1 h2 h3
    rw [piVal_append, piVal_append, piVal_cons, piVal_cons, piVal_cons, pi_of_rev,
      ← eq_inv_of_mul_eq_one_left e, mul_assoc]

/-- The tree-presentation value is an edge-path homotopy invariant. -/
theorem piVal_eq_of_homotopic {w w' : List (Fin flagL.m)} (h : EdgeHomotopic flagL w w') :
    piVal w = piVal w' := by
  induction h with
  | rel _ _ h => exact piVal_step_flagL h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih1 ih2 => exact ih1.trans ih2

/-- **The distinguished loop is not edge-path null-homotopic** in `flagL`. -/
theorem flagLoop_not_homotopic_nil : ¬ EdgeHomotopic flagL flagLoopL [] := fun h =>
  flagLoop_ne_one (by rw [piVal_eq_of_homotopic h]; simp [piVal])

end TheoremA.Leary
