module

public import RequestProject.TheoremA.Lemma31.Picture.CombMap
public import RequestProject.TheoremA.Lemma31.Picture.PermSplit

/-!
# The Euler bound `χ ≤ 2` for connected combinatorial maps

For permutations `p`, `q` of a finite set `D` of size `n`, write `c(·)` for the number of cycles
and `g(p, q)` for the number of components of the graph with edges `x — p x` and `x — q x`
(`numComponents`).  We prove the permutation inequality

    c(p) + c(q) + c(p * q) ≤ n + 2 g(p, q)                    (`numOrbits_add_le`)

and deduce, since `n = 2 c(α)` for a fixed-point-free involution `α`,

    χ(M) = c(σ) - c(α) + c(σ α) ≤ 2 g(σ, α)                   (`CombMap.euler_le`)

and in particular `χ(M) ≤ 2` for every connected map (`CombMap.euler_le_two`; the empty map has
`χ = 0`).

The proof is elementary and only uses the merge/split behaviour of one transposition (no surface
classification, no labels, `NPC`, girth or local groups).  It factors `p` one transposition at a
time: `p = swap x (p x) * p₀` with `p₀` having one more cycle.  Multiplying by the transposition
changes `c(p * q)` by `±1`; and if it joins two components of the graph of `(p₀, q)`, then `x` and
`p x` lie in different cycles of `p₀ * q` (cycles lie inside components), so `c(p * q)` drops.
This is the inductive form of the transposition-word argument (count of merges versus
component-joining steps).
-/

@[expose] public section

namespace TheoremA.Picture

open Equiv Function

/-! ### Joining two points of an equivalence relation -/

section Join

variable {D : Type*}

/-- The relation `r` together with the extra pair `(x, y)`. -/
def joinRel (r : D → D → Prop) (x y : D) (u v : D) : Prop := r u v ∨ (u = x ∧ v = y)

/-- The equivalence generated by `r` and one extra pair. -/
theorem eqvGen_joinRel_iff (r : D → D → Prop) (x y : D) {u v : D} :
    Relation.EqvGen (joinRel r x y) u v ↔ Relation.EqvGen r u v ∨
      ((Relation.EqvGen r x u ∨ Relation.EqvGen r y u) ∧
        (Relation.EqvGen r x v ∨ Relation.EqvGen r y v)) := by
  have tr : ∀ {a b c : D}, Relation.EqvGen r a b → Relation.EqvGen r b c →
      Relation.EqvGen r a c := fun h h' => h.trans _ _ _ h'
  have sy : ∀ {a b : D}, Relation.EqvGen r a b → Relation.EqvGen r b a := fun h => h.symm _ _
  constructor
  · intro h
    induction h with
    | rel u v h =>
      rcases h with h | ⟨hu, hv⟩
      · exact Or.inl (Relation.EqvGen.rel _ _ h)
      · subst hu hv
        exact Or.inr ⟨Or.inl (Relation.EqvGen.refl _), Or.inr (Relation.EqvGen.refl _)⟩
    | refl => exact Or.inl (Relation.EqvGen.refl _)
    | symm u v _ ih =>
      rcases ih with h | ⟨h1, h2⟩
      · exact Or.inl (sy h)
      · exact Or.inr ⟨h2, h1⟩
    | trans u w v _ _ ih₁ ih₂ =>
      rcases ih₁ with h1 | ⟨h1, h2⟩ <;> rcases ih₂ with h3 | ⟨h3, h4⟩
      · exact Or.inl (tr h1 h3)
      · exact Or.inr ⟨h3.imp (fun h => tr h (sy h1)) (fun h => tr h (sy h1)), h4⟩
      · exact Or.inr ⟨h1, h2.imp (fun h => tr h h3) (fun h => tr h h3)⟩
      · exact Or.inr ⟨h1, h4⟩
  · have mono : ∀ {a b : D}, Relation.EqvGen r a b → Relation.EqvGen (joinRel r x y) a b := by
      intro a b h
      induction h with
      | rel a b h => exact Relation.EqvGen.rel _ _ (Or.inl h)
      | refl => exact Relation.EqvGen.refl _
      | symm _ _ _ ih => exact ih.symm
      | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans _ _ _ ih₂
    have hxy : Relation.EqvGen (joinRel r x y) x y := Relation.EqvGen.rel _ _ (Or.inr ⟨rfl, rfl⟩)
    have hx : ∀ {a}, (Relation.EqvGen r x a ∨ Relation.EqvGen r y a) →
        Relation.EqvGen (joinRel r x y) x a := by
      rintro a (h | h)
      · exact mono h
      · exact hxy.trans _ _ _ (mono h)
    rintro (h | ⟨h1, h2⟩)
    · exact mono h
    · exact ((hx h1).symm _ _).trans _ _ _ (hx h2)

/-- If `x` and `y` are already related, the extra pair changes nothing. -/
theorem eqvGen_joinRel_of_eqvGen {r : D → D → Prop} {x y : D} (hxy : Relation.EqvGen r x y)
    {u v : D} : Relation.EqvGen (joinRel r x y) u v ↔ Relation.EqvGen r u v := by
  rw [eqvGen_joinRel_iff]
  constructor
  · rintro (h | ⟨h1, h2⟩)
    · exact h
    · have hx : ∀ {a}, (Relation.EqvGen r x a ∨ Relation.EqvGen r y a) →
          Relation.EqvGen r x a := by
        rintro a (h | h)
        · exact h
        · exact hxy.trans _ _ _ h
      exact ((hx h1).symm _ _).trans _ _ _ (hx h2)
  · exact Or.inl

/-- The number of classes of the equivalence relation generated by `r`. -/
noncomputable def numClasses (r : D → D → Prop) : ℕ := Nat.card (Quotient (Relation.EqvGen.setoid r))

theorem numClasses_congr {r s : D → D → Prop}
    (h : ∀ u v, Relation.EqvGen s u v ↔ Relation.EqvGen r u v) : numClasses s = numClasses r := by
  have : Relation.EqvGen.setoid s = Relation.EqvGen.setoid r := by
    ext u v; exact h u v
  unfold numClasses
  rw [this]

/-- **Joining two unrelated points removes exactly one class.** -/
theorem numClasses_joinRel [Finite D] {r : D → D → Prop} {x y : D}
    (hxy : ¬ Relation.EqvGen r x y) : numClasses r = numClasses (joinRel r x y) + 1 := by
  unfold numClasses
  have e : ∀ z w, (⟦z⟧ : Quotient (Relation.EqvGen.setoid r)) = ⟦w⟧ ↔ Relation.EqvGen r z w :=
    fun z w => Quotient.eq
  have e' : ∀ z w, (⟦z⟧ : Quotient (Relation.EqvGen.setoid (joinRel r x y))) = ⟦w⟧ ↔
      Relation.EqvGen (joinRel r x y) z w := fun z w => Quotient.eq
  refine nat_card_eq_add_one_of_merge
    (Quotient.map id fun u v (huv : Relation.EqvGen r u v) =>
      ((eqvGen_joinRel_iff r x y).2 (Or.inl huv)))
    (p := ⟦x⟧) (q := ⟦y⟧) ?_ ?_ ?_
  · rintro ⟨u⟩; exact ⟨⟦u⟧, rfl⟩
  · intro h; exact hxy ((e x y).1 h)
  · intro u v
    induction u using Quotient.inductionOn with | h u => ?_
    induction v using Quotient.inductionOn with | h v => ?_
    simp only [Quotient.map_mk, id, e, e', eqvGen_joinRel_iff]
    have sy : ∀ {a b : D}, Relation.EqvGen r a b → Relation.EqvGen r b a := fun h => h.symm _ _
    constructor
    · rintro (h | ⟨hx, hy⟩)
      · exact Or.inl h
      · exact Or.inr ⟨hx.imp sy sy, hy.imp sy sy⟩
    · rintro (h | ⟨hx, hy⟩)
      · exact Or.inl h
      · exact Or.inr ⟨hx.imp sy sy, hy.imp sy sy⟩

end Join

/-! ### Components of a pair of permutations -/

section Pair

variable {D : Type*}

/-- One step for the pair `(p, q)`: `x ↦ p x` or `x ↦ q x`. -/
def pairStep (p q : Perm D) (x y : D) : Prop := y = p x ∨ y = q x

/-- The number of connected components of the graph with edges `x — p x`, `x — q x`, i.e. the
number of orbits of the group generated by `p` and `q`. -/
noncomputable def numComponents (p q : Perm D) : ℕ := numClasses (pairStep p q)

variable [DecidableEq D]

/-- Every step of `(swap x y * p₀, q)` is a step of `(p₀, q)` or uses the extra pair `x — y`. -/
theorem eqvGen_pairStep_swap_mul (p₀ q : Perm D) (x y : D) {u v : D}
    (h : Relation.EqvGen (pairStep (swap x y * p₀) q) u v) :
    Relation.EqvGen (joinRel (pairStep p₀ q) x y) u v := by
  induction h with
  | rel u v h =>
    have st : ∀ a b, pairStep p₀ q a b → Relation.EqvGen (joinRel (pairStep p₀ q) x y) a b :=
      fun a b h => Relation.EqvGen.rel _ _ (Or.inl h)
    have hxy : Relation.EqvGen (joinRel (pairStep p₀ q) x y) x y :=
      Relation.EqvGen.rel _ _ (Or.inr ⟨rfl, rfl⟩)
    rcases h with rfl | rfl
    · rw [Perm.mul_apply]
      by_cases hx : p₀ u = x
      · rw [hx, swap_apply_left]
        exact (st u x (Or.inl hx.symm)).trans _ _ _ hxy
      · by_cases hy : p₀ u = y
        · rw [hy, swap_apply_right]
          exact (st u y (Or.inl hy.symm)).trans _ _ _ (hxy.symm _ _)
        · rw [swap_apply_of_ne_of_ne hx hy]
          exact st _ _ (Or.inl rfl)
    · exact st _ _ (Or.inr rfl)
  | refl => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans _ _ _ ih₂

/-- The components of `(swap x y * p₀, q)` are those of `(p₀, q)` with the components of `x` and
`y` joined, provided `x` and `y` are joined in the new graph. -/
theorem eqvGen_pairStep_swap_mul_iff (p₀ q : Perm D) (x y : D)
    (hxy : Relation.EqvGen (pairStep (swap x y * p₀) q) x y) {u v : D} :
    Relation.EqvGen (pairStep (swap x y * p₀) q) u v ↔
      Relation.EqvGen (joinRel (pairStep p₀ q) x y) u v := by
  constructor
  · exact eqvGen_pairStep_swap_mul p₀ q x y
  · intro h
    induction h with
    | rel a b hab =>
      rcases hab with hab | ⟨ha, hb⟩
      · have h1 : Relation.EqvGen (pairStep (swap x y * (swap x y * p₀)) q) a b := by
          rw [swap_mul_swap_mul]; exact Relation.EqvGen.rel _ _ hab
        exact (eqvGen_joinRel_of_eqvGen hxy).1 (eqvGen_pairStep_swap_mul _ q x y h1)
      · rw [ha, hb]; exact hxy
    | refl => exact Relation.EqvGen.refl _
    | symm _ _ _ ih => exact ih.symm
    | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans _ _ _ ih₂

omit [DecidableEq D] in
/-- The cycles of `p * q` lie inside the components of `(p, q)`. -/
theorem eqvGen_pairStep_of_sameCycle_mul [Finite D] {p q : Perm D} {u v : D}
    (h : (p * q).SameCycle u v) : Relation.EqvGen (pairStep p q) u v := by
  obtain ⟨n, rfl⟩ := h.exists_nat_pow_eq
  clear h
  induction n with
  | zero => exact Relation.EqvGen.refl _
  | succ n ih =>
    refine ih.trans _ _ _ ?_
    rw [pow_succ', Perm.mul_apply, Perm.mul_apply]
    set z := ((p * q) ^ n) u
    exact (Relation.EqvGen.rel z (q z) (Or.inr rfl)).trans _ _ _
      (Relation.EqvGen.rel (q z) (p (q z)) (Or.inl rfl))

omit [DecidableEq D] in
/-- The components of `(1, q)` are the cycles of `q`. -/
theorem sameCycle_of_eqvGen_pairStep_one [Finite D] {q : Perm D} {u v : D}
    (h : Relation.EqvGen (pairStep 1 q) u v) : q.SameCycle u v := by
  induction h with
  | rel u v h =>
    rcases h with rfl | rfl
    · exact Perm.SameCycle.refl _ _
    · exact ⟨1, by simp⟩
  | refl => exact Perm.SameCycle.refl _ _
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

omit [DecidableEq D] in
theorem numOrbits_le_numComponents_one [Finite D] (q : Perm D) :
    numOrbits q ≤ numComponents 1 q := by
  unfold numOrbits numComponents numClasses
  exact Nat.card_le_card_of_surjective
    (Quotient.map id fun u v (h : Relation.EqvGen (pairStep 1 q) u v) =>
      sameCycle_of_eqvGen_pairStep_one h)
    (by rintro ⟨u⟩; exact ⟨⟦u⟧, rfl⟩)

omit [DecidableEq D] in
theorem numOrbits_one [Finite D] : numOrbits (1 : Perm D) = Nat.card D := by
  refine numOrbits_eq_of_iff 1 id Function.surjective_id fun x y => ?_
  constructor
  · rintro rfl; exact Perm.SameCycle.refl _ _
  · rintro ⟨n, hn⟩; simpa using hn

/-- **The permutation Euler inequality**: `c(p) + c(q) + c(p q) ≤ n + 2 g(p, q)`. -/
theorem numOrbits_add_le [Fintype D] (p q : Perm D) :
    numOrbits p + numOrbits q + numOrbits (p * q) ≤ Fintype.card D + 2 * numComponents p q := by
  induction hs : p.support.card using Nat.strong_induction_on generalizing p with
  | _ k ih =>
  by_cases hp : p = 1
  · subst hp
    rw [numOrbits_one, one_mul, Nat.card_eq_fintype_card]
    have := numOrbits_le_numComponents_one q
    omega
  obtain ⟨x, hx⟩ : ∃ x, p x ≠ x := by
    by_contra h
    push_neg at h
    exact hp (Perm.ext h)
  set y := p x with hy
  set p₀ := swap x y * p with hp₀
  have hlt : p₀.support.card < k := hs ▸ Perm.card_support_swap_mul hx
  have IH := ih _ hlt p₀ rfl
  have hp_eq : p = swap x y * p₀ := (swap_mul_swap_mul x y p).symm
  have hxy : x ≠ y := hx.symm
  -- `p₀` has one more cycle than `p`
  have hc₀ : numOrbits p₀ = numOrbits p + 1 :=
    numOrbits_swap_mul_split hxy (⟨1, by simp [hy]⟩ : p.SameCycle x y)
  have hpq : p * q = swap x y * (p₀ * q) := by rw [hp_eq, mul_assoc]
  have hstep : Relation.EqvGen (pairStep (swap x y * p₀) q) x y :=
    Relation.EqvGen.rel _ _ (Or.inl (by rw [← hp_eq]))
  have hcomp : ∀ u v, Relation.EqvGen (pairStep p q) u v ↔
      Relation.EqvGen (joinRel (pairStep p₀ q) x y) u v := by
    intro u v
    rw [hp_eq]
    exact eqvGen_pairStep_swap_mul_iff p₀ q x y hstep
  by_cases hj : Relation.EqvGen (pairStep p₀ q) x y
  · have hg : numComponents p q = numComponents p₀ q := by
      unfold numComponents
      exact numClasses_congr fun u v => (hcomp u v).trans (eqvGen_joinRel_of_eqvGen hj)
    have := numOrbits_swap_mul_le x y (p₀ * q)
    rw [← hpq] at this
    omega
  · have hg : numComponents p₀ q = numComponents p q + 1 := by
      unfold numComponents
      rw [numClasses_joinRel hj, numClasses_congr hcomp]
    have hnc : ¬ (p₀ * q).SameCycle x y := fun h => hj (eqvGen_pairStep_of_sameCycle_mul h)
    have := numOrbits_swap_mul hnc
    rw [← hpq] at this
    omega

omit [DecidableEq D] in
/-- For an involution without fixed points, the cycle of `u` is `{u, α u}`. -/
theorem sameCycle_involution_iff [Finite D] {α : Perm D} (hα : ∀ d, α (α d) = d) {u v : D} :
    α.SameCycle u v ↔ v = u ∨ v = α u := by
  constructor
  · intro h
    obtain ⟨n, rfl⟩ := h.exists_nat_pow_eq
    clear h
    induction n with
    | zero => exact Or.inl rfl
    | succ n ih =>
      rw [pow_succ', Perm.mul_apply]
      rcases ih with h | h <;> rw [h]
      · exact Or.inr rfl
      · exact Or.inl (hα u)
  · rintro (rfl | rfl)
    · exact Perm.SameCycle.refl _ _
    · exact ⟨1, by simp⟩

omit [DecidableEq D] in
/-- **A fixed-point-free involution has `n / 2` cycles.** -/
theorem card_eq_two_mul_numOrbits [Finite D] {α : Perm D} (hα : ∀ d, α (α d) = d)
    (hne : ∀ d, α d ≠ d) : Nat.card D = 2 * numOrbits α := by
  classical
  unfold numOrbits
  set Q := Quotient (Perm.SameCycle.setoid α)
  have e : ∀ z w, (⟦z⟧ : Q) = ⟦w⟧ ↔ α.SameCycle z w := fun z w => Quotient.eq
  have hout : ∀ d : D, α.SameCycle (⟦d⟧ : Q).out d := fun d => (e _ _).1 (by simp)
  let f : D → Q × Bool := fun d => (⟦d⟧, decide (d = (⟦d⟧ : Q).out))
  have hf : Bijective f := by
    constructor
    · intro d d' hdd'
      simp only [f, Prod.mk.injEq] at hdd'
      obtain ⟨h1, h2⟩ := hdd'
      have hd := (sameCycle_involution_iff hα).1 (hout d)
      have hd' := (sameCycle_involution_iff hα).1 (hout d')
      rw [h1] at hd h2
      by_cases hc : d = (⟦d'⟧ : Q).out
      · have : d' = (⟦d'⟧ : Q).out := by simpa [hc] using h2
        rw [hc, ← this]
      · have hc' : d' ≠ (⟦d'⟧ : Q).out := by simpa [hc] using h2
        exact (hd.resolve_left hc).trans (hd'.resolve_left hc').symm
    · rintro ⟨q, bb⟩
      induction q using Quotient.inductionOn with | h d => ?_
      have hq : (⟦(⟦d⟧ : Q).out⟧ : Q) = ⟦d⟧ := Quotient.out_eq _
      have hq' : (⟦α (⟦d⟧ : Q).out⟧ : Q) = ⟦d⟧ := by
        rw [e]
        exact (Perm.SameCycle.symm (⟨1, by simp⟩ :
          α.SameCycle (⟦d⟧ : Q).out (α (⟦d⟧ : Q).out))).trans (hout d)
      cases bb
      · refine ⟨α (⟦d⟧ : Q).out, ?_⟩
        simp only [f, hq', Prod.mk.injEq, true_and, decide_eq_false_iff_not]
        exact hne _
      · refine ⟨(⟦d⟧ : Q).out, ?_⟩
        simp [f, hq]
  have := Nat.card_congr (Equiv.ofBijective f hf)
  rw [this, Nat.card_prod, Nat.card_eq_fintype_card (α := Bool), Fintype.card_bool]
  ring

end Pair

/-! ### The Euler bound for combinatorial maps -/

namespace CombMap

variable (M : CombMap)

/-- The number of connected components of a map. -/
noncomputable def numComponents : ℕ := Picture.numComponents M.σ M.α

theorem card_eq_two_mul_numEdges : Fintype.card M.D = 2 * M.numEdges := by
  rw [← Nat.card_eq_fintype_card]
  exact card_eq_two_mul_numOrbits M.α_α M.α_ne

/-- **Euler bound**: `χ(M) ≤ 2 · (number of components)`. -/
theorem euler_le : M.euler ≤ 2 * M.numComponents := by
  have h := numOrbits_add_le M.σ M.α
  have hn := M.card_eq_two_mul_numEdges
  unfold euler numVertices numEdges numFaces φ numComponents at *
  omega

theorem numComponents_le_one_of_connected (hM : M.Connected) : M.numComponents ≤ 1 := by
  unfold numComponents Picture.numComponents numClasses
  rw [Finite.card_le_one_iff_subsingleton]
  constructor
  rintro ⟨u⟩ ⟨v⟩
  exact Quotient.sound (hM u v)

/-- **Euler bound for connected maps**: `χ(M) ≤ 2` for every connected (orientable) combinatorial
map.  (For the empty map `χ = 0`.) -/
theorem euler_le_two (hM : M.Connected) : M.euler ≤ 2 := by
  have h1 := M.euler_le
  have h2 := M.numComponents_le_one_of_connected hM
  omega

end CombMap

end TheoremA.Picture
