module

public import RequestProject.TheoremA.RelPres.OmegaPres

/-!
# Group-theoretic properties of `Ω_R`

* `Omega.gen R` — the canonical natural-number generator sequence; `Omega.closure_range_gen`,
  `Omega.gen_eq_one_of_not_validLabel`; `Countable (Omega R)`.
* `omegaIncl R n c : G_(n,c) →* Ω_R` (tagging) and the retraction `omegaProj R n c`, with
  `omegaProj_comp_omegaIncl` and `omegaIncl_injective`.
* `FreeProdFam R` — the indexed free product `∗_{(n,c)} G_(n,c)`, and the explicit isomorphism
  `omegaEquivFreeProd : Ω_R ≃* FreeProdFam R`, compatible with the factor maps.
* `ClassCR.exists_injective_hom_omega` — every member of `C_R` embeds in `Ω_R`.
-/

@[expose] public section

namespace TheoremA.RelPres

universe u

variable {R : Set ℕ}

/-! ### General presentation lemmas -/

theorem lift_comp_hom {α G H : Type*} [Group G] [Group H] (φ : G →* H) (g : α → G)
    (r : FreeGroup α) : FreeGroup.lift (fun a => φ (g a)) r = φ (FreeGroup.lift g r) := by
  have : FreeGroup.lift (fun a => φ (g a)) = φ.comp (FreeGroup.lift g) :=
    FreeGroup.ext_hom _ _ fun a => by simp
  exact DFunLike.congr_fun this r

theorem lift_map' {α β H : Type*} [Group H] (g : β → H) (ρ : α → β) (r : FreeGroup α) :
    FreeGroup.lift g (FreeGroup.map ρ r) = FreeGroup.lift (fun a => g (ρ a)) r := by
  have : (FreeGroup.lift g).comp (FreeGroup.map ρ) = FreeGroup.lift (fun a => g (ρ a)) :=
    FreeGroup.ext_hom _ _ fun a => by simp
  exact DFunLike.congr_fun this r

theorem lift_presentedGroup_of {α : Type*} (rels : Set (FreeGroup α)) (r : FreeGroup α) :
    FreeGroup.lift (PresentedGroup.of (rels := rels)) r = PresentedGroup.mk rels r := by
  have : FreeGroup.lift (PresentedGroup.of (rels := rels)) = PresentedGroup.mk rels :=
    FreeGroup.ext_hom _ _ fun a => by simp [PresentedGroup.of]
  exact DFunLike.congr_fun this r

theorem lift_of_map_eq_mk {α β : Type*} (rels : Set (FreeGroup β)) (ρ : α → β)
    (r : FreeGroup α) :
    FreeGroup.lift (fun a => (PresentedGroup.of (ρ a) : PresentedGroup rels)) r =
      PresentedGroup.mk rels (FreeGroup.map ρ r) := by
  have : FreeGroup.lift (fun a => (PresentedGroup.of (ρ a) : PresentedGroup rels)) =
      (PresentedGroup.mk rels).comp (FreeGroup.map ρ) :=
    FreeGroup.ext_hom _ _ fun a => by simp [PresentedGroup.of]
  exact DFunLike.congr_fun this r

theorem lift_one_fun {α H : Type*} [Group H] (r : FreeGroup α) :
    FreeGroup.lift (fun _ : α => (1 : H)) r = 1 := by
  have : FreeGroup.lift (fun _ : α => (1 : H)) = 1 := FreeGroup.ext_hom _ _ fun a => by simp
  rw [this]; rfl

theorem lift_presentedGroup_of_eq_one {α : Type*} {rels : Set (FreeGroup α)} {r : FreeGroup α}
    (hr : r ∈ rels) : FreeGroup.lift (PresentedGroup.of (rels := rels)) r = 1 := by
  rw [lift_presentedGroup_of]; exact PresentedGroup.one_of_mem hr

/-! ### Generators and countability -/

/-- The canonical natural-number generator sequence of `Ω_R`. -/
def Omega.gen (R : Set ℕ) (q : ℕ) : Omega R := PresentedGroup.of q

/-- `Ω_R` is generated by the sequence `Omega.gen R`. -/
theorem Omega.closure_range_gen : Subgroup.closure (Set.range (Omega.gen R)) = ⊤ :=
  PresentedGroup.closure_range_of _

/-- Invalid generator labels are trivial in `Ω_R` (their one-letter relators). -/
theorem Omega.gen_eq_one_of_not_validLabel {q : ℕ} (h : ¬ ValidLabel q) : Omega.gen R q = 1 :=
  PresentedGroup.one_of_mem (rels := omegaRels R) (Or.inr ⟨q, h, rfl⟩)

/-- **`Ω_R` is countable** (image of the raw words on `ℕ`). -/
instance Omega.countable : Countable (Omega R) := by
  have hs : Function.Surjective fun w : RawWord ℕ => PresentedGroup.mk (omegaRels R) w.eval :=
    (QuotientGroup.mk_surjective).comp RawWord.eval_surjective
  exact hs.countable

/-! ### Factor inclusions -/

/-- The factor map `i_(n,c) : G_(n,c) →* Ω_R`, `x_a ↦ gen (tag n c a)`. -/
def omegaIncl (R : Set ℕ) (n c : ℕ) : famGroup R n c →* Omega R :=
  PresentedGroup.toGroup (f := fun a : Fin n => Omega.gen R (tag n c a)) fun r hr =>
    (lift_of_map_eq_mk (omegaRels R) (fun a : Fin n => tag n c a) r).trans
      (PresentedGroup.one_of_mem (Or.inl ⟨n, c, r, hr, rfl⟩))

@[simp] theorem omegaIncl_of (n c : ℕ) (a : Fin n) :
    omegaIncl R n c (PresentedGroup.of a) = Omega.gen R (tag n c a) :=
  PresentedGroup.toGroup.of _

/-! ### Retractions -/

/-- Values of the retraction on the natural generators. -/
noncomputable def projGen (R : Set ℕ) (n c q : ℕ) : famGroup R n c :=
  if h : labelN q = n ∧ labelC q = c ∧ labelA q < n then PresentedGroup.of ⟨labelA q, h.2.2⟩
  else 1

@[simp] theorem projGen_tag (n c : ℕ) (a : Fin n) :
    projGen R n c (tag n c a) = PresentedGroup.of a := by
  simp [projGen]

theorem projGen_tag_of_ne {n c n' c' : ℕ} (h : ¬ (n' = n ∧ c' = c)) (a : ℕ) :
    projGen R n c (tag n' c' a) = 1 := by
  simp only [projGen, labelN_tag, labelC_tag]
  rw [dif_neg]; tauto

theorem projGen_of_not_validLabel {n c q : ℕ} (h : ¬ ValidLabel q) : projGen R n c q = 1 := by
  simp only [projGen]
  rw [dif_neg]
  rintro ⟨h1, -, h3⟩
  exact h (by unfold ValidLabel; omega)

/-- The retraction `p_(n,c) : Ω_R →* G_(n,c)`: the label `⟪⟪n', c'⟫, a⟫` goes to `x_a` if
`(n', c') = (n, c)` and `a < n`, and to `1` otherwise. -/
noncomputable def omegaProj (R : Set ℕ) (n c : ℕ) : Omega R →* famGroup R n c :=
  PresentedGroup.toGroup (f := projGen R n c) fun r hr => by
    rcases hr with ⟨n', c', r₀, hr₀, rfl⟩ | ⟨q, hq, rfl⟩
    · rw [lift_map']
      by_cases h : n' = n ∧ c' = c
      · obtain ⟨rfl, rfl⟩ := h
        simp only [projGen_tag]
        exact lift_presentedGroup_of_eq_one hr₀
      · simp only [projGen_tag_of_ne h]
        exact lift_one_fun r₀
    · rw [FreeGroup.lift_apply_of]
      exact projGen_of_not_validLabel hq

@[simp] theorem omegaProj_gen (n c q : ℕ) : omegaProj R n c (Omega.gen R q) = projGen R n c q :=
  PresentedGroup.toGroup.of _

/-- **`p_(n,c) ∘ i_(n,c) = id`.** -/
theorem omegaProj_comp_omegaIncl (n c : ℕ) :
    (omegaProj R n c).comp (omegaIncl R n c) = MonoidHom.id _ :=
  PresentedGroup.ext fun a => by simp

/-- **Factor injectivity.** -/
theorem omegaIncl_injective (n c : ℕ) : Function.Injective (omegaIncl R n c) := by
  intro x y h
  have := congrArg (omegaProj R n c) h
  simpa [← MonoidHom.comp_apply, omegaProj_comp_omegaIncl] using this

/-! ### The free-product identification -/

/-- The indexed free product `∗_{(n,c) ∈ ℕ × ℕ} G_(n,c)`. -/
abbrev FreeProdFam (R : Set ℕ) : Type := Monoid.CoprodI fun i : ℕ × ℕ => famGroup R i.1 i.2

/-- The factor inclusion `G_(n,c) →* ∗ G_(n,c)`. -/
def famOf (R : Set ℕ) (n c : ℕ) : famGroup R n c →* FreeProdFam R :=
  Monoid.CoprodI.of (M := fun i : ℕ × ℕ => famGroup R i.1 i.2) (i := (n, c))

/-- Images of the natural generators in the free product. -/
noncomputable def freeGen (R : Set ℕ) (q : ℕ) : FreeProdFam R :=
  if h : ValidLabel q then famOf R (labelN q) (labelC q) (PresentedGroup.of ⟨labelA q, h⟩)
  else 1

theorem famOf_of_congr {n c n' c' a' : ℕ} (a : Fin n) (h : a' < n') (hn : n' = n)
    (hc : c' = c) (ha : a' = a.val) :
    famOf R n' c' (PresentedGroup.of ⟨a', h⟩) = famOf R n c (PresentedGroup.of a) := by
  subst hn hc ha; rfl

@[simp] theorem freeGen_tag (n c : ℕ) (a : Fin n) :
    freeGen R (tag n c a) = famOf R n c (PresentedGroup.of a) := by
  have hv : ValidLabel (tag n c a) := validLabel_tag.2 a.2
  rw [freeGen, dif_pos hv]
  exact famOf_of_congr a _ (labelN_tag _ _ _) (labelC_tag _ _ _) (labelA_tag _ _ _)

/-- `Ω_R →* ∗ G_(n,c)`: valid labels go to the canonical generators of their factors, invalid
labels go to `1`. -/
noncomputable def omegaToFreeProd (R : Set ℕ) : Omega R →* FreeProdFam R :=
  PresentedGroup.toGroup (f := freeGen R) fun r hr => by
    rcases hr with ⟨n, c, r₀, hr₀, rfl⟩ | ⟨q, hq, rfl⟩
    · rw [lift_map']
      simp only [freeGen_tag]
      exact (lift_comp_hom (famOf R n c) PresentedGroup.of r₀).trans
        (by rw [lift_presentedGroup_of_eq_one hr₀, map_one])
    · rw [FreeGroup.lift_apply_of, freeGen, dif_neg hq]

/-- `∗ G_(n,c) →* Ω_R`, induced by the factor maps `i_(n,c)`. -/
def freeProdToOmega (R : Set ℕ) : FreeProdFam R →* Omega R :=
  Monoid.CoprodI.lift fun i => omegaIncl R i.1 i.2

@[simp] theorem omegaToFreeProd_gen (q : ℕ) : omegaToFreeProd R (Omega.gen R q) = freeGen R q :=
  PresentedGroup.toGroup.of _

@[simp] theorem freeProdToOmega_famOf (n c : ℕ) (x : famGroup R n c) :
    freeProdToOmega R (famOf R n c x) = omegaIncl R n c x :=
  Monoid.CoprodI.lift_of _ x

theorem freeProdToOmega_freeGen (q : ℕ) : freeProdToOmega R (freeGen R q) = Omega.gen R q := by
  by_cases h : ValidLabel q
  · rw [freeGen, dif_pos h, freeProdToOmega_famOf, omegaIncl_of]
    simp only [tag_label]
  · rw [freeGen, dif_neg h, map_one, Omega.gen_eq_one_of_not_validLabel h]

theorem omegaToFreeProd_comp_omegaIncl (n c : ℕ) :
    (omegaToFreeProd R).comp (omegaIncl R n c) = famOf R n c :=
  PresentedGroup.ext fun a => by simp

theorem freeProdToOmega_comp_omegaToFreeProd :
    (freeProdToOmega R).comp (omegaToFreeProd R) = MonoidHom.id _ :=
  PresentedGroup.ext fun q => by
    change freeProdToOmega R (omegaToFreeProd R (Omega.gen R q)) = Omega.gen R q
    rw [omegaToFreeProd_gen, freeProdToOmega_freeGen]

theorem omegaToFreeProd_comp_freeProdToOmega :
    (omegaToFreeProd R).comp (freeProdToOmega R) = MonoidHom.id _ := by
  refine Monoid.CoprodI.ext_hom _ _ fun i => ?_
  change (omegaToFreeProd R).comp ((freeProdToOmega R).comp (famOf R i.1 i.2)) =
    (MonoidHom.id _).comp (famOf R i.1 i.2)
  rw [show (freeProdToOmega R).comp (famOf R i.1 i.2) = omegaIncl R i.1 i.2 from
    MonoidHom.ext fun x => freeProdToOmega_famOf _ _ x, omegaToFreeProd_comp_omegaIncl,
    MonoidHom.id_comp]

/-- **`Ω_R` is the free product of the groups `G_(n,c)`.** -/
noncomputable def omegaEquivFreeProd (R : Set ℕ) : Omega R ≃* FreeProdFam R :=
  MonoidHom.toMulEquiv (omegaToFreeProd R) (freeProdToOmega R)
    freeProdToOmega_comp_omegaToFreeProd omegaToFreeProd_comp_freeProdToOmega

@[simp] theorem omegaEquivFreeProd_gen (q : ℕ) :
    omegaEquivFreeProd R (Omega.gen R q) = freeGen R q :=
  omegaToFreeProd_gen q

/-- Compatibility with the factor maps: `i_(n,c)` corresponds to the factor inclusion. -/
@[simp] theorem omegaEquivFreeProd_omegaIncl (n c : ℕ) (x : famGroup R n c) :
    omegaEquivFreeProd R (omegaIncl R n c x) = famOf R n c x := by
  change omegaToFreeProd R (omegaIncl R n c x) = _
  rw [← MonoidHom.comp_apply, omegaToFreeProd_comp_omegaIncl]

@[simp] theorem omegaEquivFreeProd_symm_famOf (n c : ℕ) (x : famGroup R n c) :
    (omegaEquivFreeProd R).symm (famOf R n c x) = omegaIncl R n c x :=
  freeProdToOmega_famOf n c x

/-! ### Universality for `C_R` -/

/-- **Every member of `C_R` embeds in `Ω_R`.** -/
theorem ClassCR.exists_injective_hom_omega {X : Type u} [Group X] (h : ClassCR R X) :
    ∃ f : X →* Omega R, Function.Injective f := by
  obtain ⟨n, c, ⟨ψ⟩⟩ := h.exists_famGroup_equiv
  exact ⟨(omegaIncl R n c).comp ψ.symm.toMonoidHom,
    (omegaIncl_injective n c).comp ψ.symm.injective⟩

end TheoremA.RelPres
