module

public import Mathlib.GroupTheory.CoprodI
public import Mathlib.GroupTheory.FreeGroup.Reduce

/-!
# Normal forms in free products and free groups

Tools built on Mathlib's reduced words `Monoid.CoprodI.Word`:

* `NF.eq_of_lprod_eq` — two reduced letter lists with the same product are equal;
* `NF.cmap` — the free product of a family of homomorphisms; `NF.cmap_injective` (for injective
  factors) and `NF.mem_range_cmap_iff` (membership in the image is read off the reduced word);
* `NF.altL` — alternating letter lists in a two-factor free product (indexed by `Bool`), with
  `NF.eq_of_altProd_eq` (equal alternating products with the same `false`-pieces have the same
  `true`-pieces) and `NF.altProd_not_mem_range` (a nonempty alternating product is not in the
  `false` factor);
* `NF.mem_closure_of_iff` — in a free group, the subgroup generated by a set of generators
  consists of the elements whose reduced word uses only those generators, and
  `NF.closure_of_inf_closure_of`.
-/

@[expose] public section

namespace TheoremA.NF

open Monoid

section CoprodI

variable {ι : Type*} {M : ι → Type*} [∀ i, Group (M i)]

/-- A reduced letter list: no letter is `1`, adjacent letters come from different factors. -/
def Red (L : List (Σ i, M i)) : Prop :=
  (∀ l ∈ L, l.2 ≠ 1) ∧ L.IsChain (fun l l' => l.1 ≠ l'.1)

/-- The product of a letter list. -/
def lprod (L : List (Σ i, M i)) : CoprodI M := (L.map fun l => CoprodI.of l.2).prod

@[simp] theorem lprod_nil : lprod ([] : List (Σ i, M i)) = 1 := rfl

@[simp] theorem lprod_cons (l : Σ i, M i) (L : List (Σ i, M i)) :
    lprod (l :: L) = CoprodI.of l.2 * lprod L := by simp [lprod]

@[simp] theorem lprod_append (L L' : List (Σ i, M i)) :
    lprod (L ++ L') = lprod L * lprod L' := by simp [lprod]

/-- The reduced word of a reduced list. -/
def toWord' (L : List (Σ i, M i)) (h : Red L) : CoprodI.Word M := ⟨L, h.1, h.2⟩

theorem prod_toWord' (L : List (Σ i, M i)) (h : Red L) : (toWord' L h).prod = lprod L := rfl

/-- **Uniqueness of reduced lists.** -/
theorem eq_of_lprod_eq {L L' : List (Σ i, M i)} (h : Red L) (h' : Red L')
    (he : lprod L = lprod L') : L = L' := by
  classical
  have : toWord' L h = toWord' L' h' := CoprodI.Word.equiv.symm.injective he
  exact congrArg CoprodI.Word.toList this

/-- Every element is the product of a reduced list. -/
theorem exists_red (x : CoprodI M) : ∃ L : List (Σ i, M i), Red L ∧ lprod L = x := by
  classical
  exact ⟨(CoprodI.Word.equiv x).toList, ⟨(CoprodI.Word.equiv x).ne_one,
    (CoprodI.Word.equiv x).chain_ne⟩, CoprodI.Word.equiv.symm_apply_apply x⟩

theorem red_nil : Red ([] : List (Σ i, M i)) := ⟨by simp, List.IsChain.nil⟩

theorem red_singleton {i : ι} (m : M i) (hm : m ≠ 1) : Red [(⟨i, m⟩ : Σ i, M i)] :=
  ⟨by simpa using hm, List.isChain_singleton _⟩

theorem Red.tail {l : Σ i, M i} {L : List (Σ i, M i)} (h : Red (l :: L)) : Red L :=
  ⟨fun x hx => h.1 x (List.mem_cons_of_mem _ hx), h.2.tail⟩

/-! ### Free products of homomorphisms -/

variable {N : ι → Type*} [∀ i, Group (N i)]

/-- The free product of a family of homomorphisms. -/
def cmap (f : ∀ i, M i →* N i) : CoprodI M →* CoprodI N :=
  CoprodI.lift fun i => (CoprodI.of : N i →* CoprodI N).comp (f i)

@[simp] theorem cmap_of (f : ∀ i, M i →* N i) {i : ι} (m : M i) :
    cmap f (CoprodI.of m) = CoprodI.of (f i m) := by simp [cmap]

/-- Letterwise image of a list. -/
def lmap (f : ∀ i, M i →* N i) (L : List (Σ i, M i)) : List (Σ i, N i) :=
  L.map fun l => ⟨l.1, f l.1 l.2⟩

theorem cmap_lprod (f : ∀ i, M i →* N i) (L : List (Σ i, M i)) :
    cmap f (lprod L) = lprod (lmap f L) := by
  induction L with
  | nil => simp [lmap]
  | cons l L ih => simp [lmap, ih] at *

theorem red_lmap {f : ∀ i, M i →* N i} (hf : ∀ i, Function.Injective (f i))
    {L : List (Σ i, M i)} (h : Red L) : Red (lmap f L) := by
  refine ⟨?_, ?_⟩
  · intro l hl
    obtain ⟨l₀, hl₀, rfl⟩ := List.mem_map.1 hl
    exact fun h1 => h.1 l₀ hl₀ ((hf l₀.1) (by simpa using h1))
  · exact List.isChain_map_of_isChain (fun l : Σ i, M i => (⟨l.1, f l.1 l.2⟩ : Σ i, N i))
      (fun a b hab => hab) h.2

theorem lmap_injective {f : ∀ i, M i →* N i} (hf : ∀ i, Function.Injective (f i)) :
    Function.Injective (lmap f) := by
  intro L L' h
  apply List.map_injective_iff.2 _ h
  rintro ⟨i, m⟩ ⟨j, m'⟩ he
  simp only [Sigma.mk.injEq] at he
  obtain ⟨rfl, he⟩ := he
  rw [heq_iff_eq] at he
  rw [hf i he]

/-- **Free products of injective homomorphisms are injective.** -/
theorem cmap_injective {f : ∀ i, M i →* N i} (hf : ∀ i, Function.Injective (f i)) :
    Function.Injective (cmap f) := by
  intro x y hxy
  obtain ⟨L, hL, rfl⟩ := exists_red x
  obtain ⟨L', hL', rfl⟩ := exists_red y
  rw [cmap_lprod, cmap_lprod] at hxy
  rw [lmap_injective hf (eq_of_lprod_eq (red_lmap hf hL) (red_lmap hf hL') hxy)]

/-- **Membership in the image of a free product of injective homomorphisms**: every letter of
the reduced word lies in the image of the corresponding factor. -/
theorem mem_range_cmap_iff {f : ∀ i, M i →* N i} (hf : ∀ i, Function.Injective (f i))
    {L : List (Σ i, N i)} (hL : Red L) :
    lprod L ∈ (cmap f).range ↔ ∀ l ∈ L, l.2 ∈ (f l.1).range := by
  constructor
  · rintro ⟨x, hx⟩
    obtain ⟨L₀, hL₀, rfl⟩ := exists_red x
    rw [cmap_lprod] at hx
    rw [← eq_of_lprod_eq (red_lmap hf hL₀) hL hx]
    intro l hl
    obtain ⟨l₀, -, rfl⟩ := List.mem_map.1 hl
    exact ⟨l₀.2, rfl⟩
  · intro h
    induction L with
    | nil => exact ⟨1, by simp⟩
    | cons l L ih =>
      obtain ⟨y, hy⟩ := ih hL.tail (fun l' hl' => h l' (List.mem_cons_of_mem _ hl'))
      obtain ⟨m, hm⟩ := h l (List.mem_cons_self)
      refine ⟨CoprodI.of m * y, ?_⟩
      rw [map_mul, hy, cmap_of, hm, lprod_cons]

end CoprodI

/-! ### Alternating products in a two-factor free product -/

section Alt

variable {P : Bool → Type*} [∀ b, Group (P b)]

open Classical in
/-- The optional `false`-letter. -/
noncomputable def optF (a : P false) : List (Σ b, P b) := if a = 1 then [] else [⟨false, a⟩]

/-- The alternating list `a₀ b₁ a₁ ⋯ bₙ aₙ`, omitting trivial `false`-pieces. -/
noncomputable def altL (a₀ : P false) : List (P true × P false) → List (Σ b, P b)
  | [] => optF a₀
  | p :: L => optF a₀ ++ ⟨true, p.1⟩ :: altL p.2 L

theorem lprod_optF (a : P false) : lprod (optF a) = CoprodI.of a := by
  unfold optF; split_ifs with h <;> simp [h]

/-- The product of an alternating list. -/
def altProd (a₀ : P false) : List (P true × P false) → CoprodI P
  | [] => CoprodI.of a₀
  | p :: L => CoprodI.of a₀ * CoprodI.of p.1 * altProd p.2 L

theorem lprod_altL (a₀ : P false) (L : List (P true × P false)) :
    lprod (altL a₀ L) = altProd a₀ L := by
  induction L generalizing a₀ with
  | nil => simp [altL, altProd, lprod_optF]
  | cons p L ih => simp [altL, altProd, lprod_optF, ih, mul_assoc]

/-- Admissibility: `true`-pieces nontrivial, internal `false`-pieces nontrivial. -/
def AltOK : List (P true × P false) → Prop
  | [] => True
  | [p] => p.1 ≠ 1
  | p :: q :: L => p.1 ≠ 1 ∧ p.2 ≠ 1 ∧ AltOK (q :: L)

theorem altL_head (a₀ : P false) (L : List (P true × P false)) (ha : a₀ ≠ 1) :
    (altL a₀ L).head? = some ⟨false, a₀⟩ := by
  cases L <;> simp [altL, optF, ha]

theorem red_altL : ∀ (a₀ : P false) (L : List (P true × P false)), AltOK L → Red (altL a₀ L)
  | a₀, [], _ => by
    unfold altL optF; split_ifs with h
    · exact red_nil
    · exact red_singleton _ h
  | a₀, [p], h => by
    have h1 : p.1 ≠ 1 := h
    rw [altL, altL]
    unfold optF
    refine ⟨?_, ?_⟩
    · intro l hl
      split_ifs at hl with h2 h3 <;>
        simp only [List.nil_append, List.cons_append, List.mem_cons,
          List.not_mem_nil, or_false] at hl <;>
        rcases hl with rfl | rfl | rfl <;> assumption
    · split_ifs <;> simp
  | a₀, p :: q :: L, h => by
    obtain ⟨h1, h2, h3⟩ := h
    have ih := red_altL p.2 (q :: L) h3
    have hhead := altL_head p.2 (q :: L) h2
    rw [altL]
    refine ⟨?_, ?_⟩
    · intro l hl
      rcases List.mem_append.1 hl with hl | hl
      · unfold optF at hl; split_ifs at hl with h4
        · simp at hl
        · simp only [List.mem_singleton] at hl; subst hl; exact h4
      · rcases List.mem_cons.1 hl with rfl | hl
        · exact h1
        · exact ih.1 l hl
    · have hc : (⟨true, p.1⟩ :: altL p.2 (q :: L) : List (Σ b, P b)).IsChain
          (fun l l' => l.1 ≠ l'.1) := by
        obtain ⟨T, hT⟩ : ∃ T, altL p.2 (q :: L) = ⟨false, p.2⟩ :: T := by
          cases hA : altL p.2 (q :: L) with
          | nil => rw [hA] at hhead; simp at hhead
          | cons x T => rw [hA] at hhead; simp at hhead; exact ⟨T, by rw [← hhead]⟩
        rw [hT] at ih ⊢
        exact List.IsChain.cons_cons (by simp) ih.2
      unfold optF; split_ifs
      · simpa using hc
      · exact List.IsChain.cons_cons (by simp) hc

omit [∀ b, Group (P b)] in
/-- Extract the `true`-letters. -/
def trueLetters : List (Σ b, P b) → List (P true)
  | [] => []
  | ⟨true, x⟩ :: L => x :: trueLetters L
  | ⟨false, _⟩ :: L => trueLetters L

omit [∀ b, Group (P b)] in
theorem trueLetters_append (L L' : List (Σ b, P b)) :
    trueLetters (L ++ L') = trueLetters L ++ trueLetters L' := by
  induction L with
  | nil => rfl
  | cons l L ih => rcases l with ⟨_ | _, x⟩ <;> simp [trueLetters, ih]

theorem trueLetters_optF (a : P false) : trueLetters (optF a) = [] := by
  unfold optF; split_ifs <;> rfl

theorem trueLetters_altL (a₀ : P false) (L : List (P true × P false)) :
    trueLetters (altL a₀ L) = L.map Prod.fst := by
  induction L generalizing a₀ with
  | nil => simp [altL, trueLetters_optF]
  | cons p L ih => simp [altL, trueLetters_append, trueLetters_optF, trueLetters, ih]

/-- **Equal alternating products have equal `true`-pieces.** -/
theorem eq_of_altProd_eq {a₀ a₀' : P false} {L L' : List (P true × P false)} (h : AltOK L)
    (h' : AltOK L') (he : altProd a₀ L = altProd a₀' L') : L.map Prod.fst = L'.map Prod.fst := by
  rw [← lprod_altL, ← lprod_altL] at he
  have := eq_of_lprod_eq (red_altL _ _ h) (red_altL _ _ h') he
  rw [← trueLetters_altL a₀, this, trueLetters_altL]

/-- **A nonempty admissible alternating product is not in the `false` factor.** -/
theorem altProd_not_mem_range {a₀ : P false} {L : List (P true × P false)} (h : AltOK L)
    (hL : L ≠ []) (a : P false) : altProd a₀ L ≠ CoprodI.of a := by
  intro he
  have he' : altProd a₀ L = altProd a [] := he
  rw [← lprod_altL, ← lprod_altL] at he'
  have := eq_of_lprod_eq (red_altL _ _ h) (red_altL a [] trivial) he'
  have h2 := congrArg trueLetters this
  rw [trueLetters_altL, trueLetters_altL] at h2
  exact hL (List.map_eq_nil_iff.1 h2)

end Alt

/-! ### Subgroups generated by generators of a free group -/

section FreeGroupLetters

variable {X : Type*} [DecidableEq X]

theorem letters_reduce_subset (L : List (X × Bool)) :
    ∀ p ∈ FreeGroup.reduce L, p ∈ L :=
  fun _ hp => (FreeGroup.reduce.red).sublist.subset hp

/-- **Letters criterion.** -/
theorem mem_closure_of_iff (A : Set X) (x : FreeGroup X) :
    x ∈ Subgroup.closure (FreeGroup.of '' A) ↔ ∀ p ∈ x.toWord, p.1 ∈ A := by
  constructor
  · intro hx
    induction hx using Subgroup.closure_induction with
    | mem y hy =>
      obtain ⟨a, ha, rfl⟩ := hy
      intro p hp
      rw [FreeGroup.toWord_of] at hp
      simp only [List.mem_singleton] at hp
      subst hp; exact ha
    | one => simp
    | mul y z _ _ hy hz =>
      intro p hp
      rw [FreeGroup.toWord_mul] at hp
      rcases List.mem_append.1 (letters_reduce_subset _ p hp) with h | h
      · exact hy p h
      · exact hz p h
    | inv y _ hy =>
      intro p hp
      rw [FreeGroup.toWord_inv] at hp
      simp only [FreeGroup.invRev, List.mem_reverse, List.mem_map] at hp
      obtain ⟨q, hq, rfl⟩ := hp
      exact hy q hq
  · intro h
    rw [← FreeGroup.mk_toWord (x := x)]
    suffices H : ∀ L : List (X × Bool), (∀ p ∈ L, p.1 ∈ A) →
        FreeGroup.mk L ∈ Subgroup.closure (FreeGroup.of '' A) from H _ h
    intro L hL
    induction L with
    | nil => exact Subgroup.one_mem _
    | cons p L ih =>
      rw [← List.singleton_append, ← FreeGroup.mul_mk]
      refine Subgroup.mul_mem _ ?_ (ih fun q hq => hL q (List.mem_cons_of_mem _ hq))
      obtain ⟨a, b⟩ := p
      have ha : a ∈ A := hL (a, b) List.mem_cons_self
      cases b
      · have : (FreeGroup.mk [(a, false)] : FreeGroup X) = (FreeGroup.of a)⁻¹ := by
          show _ = (FreeGroup.mk [(a, true)])⁻¹
          rw [FreeGroup.inv_mk]; rfl
        rw [this]
        exact Subgroup.inv_mem _ (Subgroup.subset_closure ⟨a, ha, rfl⟩)
      · exact Subgroup.subset_closure ⟨a, ha, rfl⟩

/-- **Intersections of subgroups generated by sets of generators.** -/
theorem closure_of_inf_closure_of (A B : Set X) :
    Subgroup.closure (FreeGroup.of '' A) ⊓ Subgroup.closure (FreeGroup.of '' B) =
      Subgroup.closure (FreeGroup.of '' (A ∩ B)) := by
  ext x
  simp only [Subgroup.mem_inf, mem_closure_of_iff, Set.mem_inter_iff]
  exact ⟨fun h p hp => ⟨h.1 p hp, h.2 p hp⟩, fun h => ⟨fun p hp => (h p hp).1,
    fun p hp => (h p hp).2⟩⟩

end FreeGroupLetters

end TheoremA.NF
