module

public import RequestProject.TheoremA.RelPres.FP2Bridge
public import RequestProject.TheoremA.RelPres.HNN
public import RequestProject.TheoremA.RelPres.Diagram
public import RequestProject.TheoremA.RelPres.TwoGen
public import RequestProject.TheoremA.Groups.IsFPTransport

/-!
# Finite relative presentations of actual groups

Let `ψ : PresentedGroup S ≃* B` be a presentation of `B` on the alphabet `Fin n`.  A group `E`
with a homomorphism `i : B →* E` and `k` further elements `y : Fin k → E` is *finitely presented
relative to `B`* by a finite list `U` of raw words on `Fin (n + k)` if

* the words of `U` evaluate to `1` in `E` (old letters ↦ `i (ψ (of j))`, new letters ↦ `y l`),
* there is a homomorphism `β : E →* P`, `P = ⟨Fin (n+k) | castAdd(S) ∪ U⟩`, sending `i b` to the
  image of `b` and `y l` to the `l`-th new letter, and
* `E` is generated by `i(B)` and the `y l` (stated as: an endomorphism of `E` fixing `i(B)`
  pointwise and every `y l` is the identity).

Then `relPresEquiv : P ≃* E`.  Consequently (`classCR_of_relPres`, `isFP_two_of_relPres`)
`E ∈ C_R` whenever `B ∈ C_R` (same oracle `R`), and `E` is `FP₂` whenever `B` is.

Free products: `coprodPresEquiv` presents `B₀ ∗ B₁` (Mathlib's `Monoid.Coprod`) on
`Fin (n₀ + n₁)` by the union of the two renamed relator sets; `ClassCR.coprod` and
`isFP_two_coprod`.
-/

@[expose] public section

namespace TheoremA.RelPres

open PresentedGroup

universe u v w

/-! ### One source -/

section OneSource

variable {B : Type u} [Group B] {E : Type v} [Group E] {n k : ℕ} {S : Set (FreeGroup (Fin n))}

/-- The relator set `castAdd(S) ∪ U` on `Fin (n + k)`. -/
def relExt (S : Set (FreeGroup (Fin n))) (k : ℕ) (U : List (RawWord (Fin (n + k)))) :
    Set (FreeGroup (Fin (n + k))) :=
  FreeGroup.map (Fin.castAdd k) '' S ∪ RawWord.eval '' {w | w ∈ U}

/-- The homomorphism `PresentedGroup S → PresentedGroup (relExt S k U)` on old letters. -/
noncomputable def relBaseAux (S : Set (FreeGroup (Fin n))) (k : ℕ)
    (U : List (RawWord (Fin (n + k)))) : PresentedGroup S →* PresentedGroup (relExt S k U) :=
  PresentedGroup.toGroup (f := fun i => of (Fin.castAdd k i)) (by
    intro r hr
    rw [lift_of_map_eq_mk]
    exact PresentedGroup.one_of_mem (Or.inl ⟨r, hr, rfl⟩))

/-- The base homomorphism `B → PresentedGroup (relExt S k U)`. -/
noncomputable def relBase (ψ : PresentedGroup S ≃* B) (k : ℕ) (U : List (RawWord (Fin (n + k)))) :
    B →* PresentedGroup (relExt S k U) :=
  (relBaseAux S k U).comp (ψ.symm : B →* PresentedGroup S)

theorem relBase_gen (ψ : PresentedGroup S ≃* B) (k : ℕ) (U : List (RawWord (Fin (n + k))))
    (i : Fin n) : relBase ψ k U (ψ (of i)) = of (Fin.castAdd k i) := by
  simp [relBase, relBaseAux, PresentedGroup.toGroup.of]

theorem relBase_mk (ψ : PresentedGroup S ≃* B) (k : ℕ) (U : List (RawWord (Fin (n + k))))
    (x : FreeGroup (Fin n)) :
    relBase ψ k U (ψ (PresentedGroup.mk S x)) =
      PresentedGroup.mk (relExt S k U) (FreeGroup.map (Fin.castAdd k) x) := by
  simp only [relBase, relBaseAux, MonoidHom.comp_apply, MonoidHom.coe_coe,
    MulEquiv.symm_apply_apply, toGroup_mk, lift_of_map_eq_mk]

/-- The generator assignment for the forward map. -/
def relGens (ψ : PresentedGroup S ≃* B) (i : B →* E) (y : Fin k → E) : Fin (n + k) → E :=
  Fin.append (fun j => i (ψ (of j))) y

theorem lift_relGens_castAdd (ψ : PresentedGroup S ≃* B) (i : B →* E) (y : Fin k → E)
    (x : FreeGroup (Fin n)) :
    FreeGroup.lift (relGens ψ i y) (FreeGroup.map (Fin.castAdd k) x) =
      i (ψ (PresentedGroup.mk S x)) := by
  rw [lift_map']
  simp only [relGens, Fin.append_left]
  exact lift_presentation ψ i x

variable (ψ : PresentedGroup S ≃* B) (i : B →* E) (y : Fin k → E) (U : List (RawWord (Fin (n + k))))

/-- **Forward map** of a finite relative presentation. -/
noncomputable def relFwd (hU : ∀ u ∈ U, FreeGroup.lift (relGens ψ i y) u.eval = 1) :
    PresentedGroup (relExt S k U) →* E :=
  PresentedGroup.toGroup (f := relGens ψ i y) (by
    rintro r (⟨s, hs, rfl⟩ | ⟨u, hu, rfl⟩)
    · rw [lift_relGens_castAdd, PresentedGroup.one_of_mem hs, map_one, map_one]
    · exact hU u hu)

theorem relFwd_of (hU : ∀ u ∈ U, FreeGroup.lift (relGens ψ i y) u.eval = 1) (x : Fin (n + k)) :
    relFwd ψ i y U hU (of x) = relGens ψ i y x := by
  simp [relFwd, PresentedGroup.toGroup.of]

theorem relFwd_relBase (hU : ∀ u ∈ U, FreeGroup.lift (relGens ψ i y) u.eval = 1) (b : B) :
    relFwd ψ i y U hU (relBase ψ k U b) = i b := by
  have : (relFwd ψ i y U hU).comp (relBase ψ k U) = i := by
    apply hom_ext_presentation ψ
    intro j
    simp [relBase_gen, relFwd_of, relGens]
  exact DFunLike.congr_fun this b

/-- **Finite relative presentation theorem.**  Under the three hypotheses listed in the module
docstring, `PresentedGroup (relExt S k U) ≃* E`. -/
noncomputable def relPresEquiv (hU : ∀ u ∈ U, FreeGroup.lift (relGens ψ i y) u.eval = 1)
    (β : E →* PresentedGroup (relExt S k U)) (hβi : ∀ b, β (i b) = relBase ψ k U b)
    (hβy : ∀ l, β (y l) = of (Fin.natAdd n l))
    (hgen : ∀ f : E →* E, f.comp i = i → (∀ l, f (y l) = y l) → f = MonoidHom.id E) :
    PresentedGroup (relExt S k U) ≃* E :=
  MonoidHom.toMulEquiv (relFwd ψ i y U hU) β
    (by
      apply PresentedGroup.ext
      intro x
      refine Fin.addCases (fun j => ?_) (fun l => ?_) x
      · simp only [MonoidHom.comp_apply, relFwd_of, relGens, Fin.append_left, hβi, relBase_gen,
          MonoidHom.id_apply]
      · simp only [MonoidHom.comp_apply, relFwd_of, relGens, Fin.append_right, hβy,
          MonoidHom.id_apply])
    (by
      apply hgen
      · ext b
        simp [hβi, relFwd_relBase]
      · intro l
        simp [hβy, relFwd_of, relGens])

theorem relPresEquiv_of_castAdd (hU) (β : E →* PresentedGroup (relExt S k U)) (hβi hβy hgen)
    (j : Fin n) :
    relPresEquiv ψ i y U hU β hβi hβy hgen (of (Fin.castAdd k j)) = i (ψ (of j)) := by
  simp [relPresEquiv, relFwd_of, relGens]

theorem relPresEquiv_of_natAdd (hU) (β : E →* PresentedGroup (relExt S k U)) (hβi hβy hgen)
    (l : Fin k) :
    relPresEquiv ψ i y U hU β hβi hβy hgen (of (Fin.natAdd n l)) = y l := by
  simp [relPresEquiv, relFwd_of, relGens]

end OneSource

/-- **`C_R` transfer** along a finite relative presentation (same oracle `R`). -/
theorem classCR_of_relPres {R : Set ℕ} {E : Type v} [Group E] {n k : ℕ}
    {e : ℕ →. RawWord (Fin n)} (he : IsEnumerator R e) (U : List (RawWord (Fin (n + k))))
    (Φ : PresentedGroup (relExt (enumRelators e) k U) ≃* E) : ClassCR R E :=
  ⟨n + k, extendEnum e (Fin.castAdd k) U, he.extendEnum _ _,
    ⟨(MulEquiv.cast (by rw [enumRelators_extendEnum]; rfl)).trans Φ⟩⟩
where
  /-- auxiliary cast between presented groups with equal relator sets -/
  MulEquiv.cast {α : Type} {r r' : Set (FreeGroup α)} (h : r = r') :
      PresentedGroup r ≃* PresentedGroup r' := by subst h; exact MulEquiv.refl _

/-- `C_R` transfer, for a relator set equal to an enumerated one. -/
theorem classCR_of_relPres' {R : Set ℕ} {E : Type v} [Group E] {n k : ℕ}
    {e : ℕ →. RawWord (Fin n)} {S : Set (FreeGroup (Fin n))} (he : IsEnumerator R e)
    (hS : enumRelators e = S) (U : List (RawWord (Fin (n + k))))
    (Φ : PresentedGroup (relExt S k U) ≃* E) : ClassCR R E := by
  subst hS
  exact classCR_of_relPres he U Φ

/-- **`FP₂` transfer** along a finite relative presentation. -/
theorem isFP_two_of_relPres {B : Type u} [Group B] {E : Type v} [Group E] {n k : ℕ}
    {S : Set (FreeGroup (Fin n))} (ψ : PresentedGroup S ≃* B) (hB : IsFP 2 B)
    (U : List (RawWord (Fin (n + k)))) (Φ : PresentedGroup (relExt S k U) ≃* E) : IsFP 2 E := by
  have hS : IsFP 2 (PresentedGroup S) := IsFP.of_mulEquiv ψ.symm hB
  have h := isFP_two_presentedGroup_subst_union_finite S (FreeGroup.map (Fin.castAdd k))
    (RawWord.eval '' {w | w ∈ U}) ((List.finite_toSet U).image _) hS
  exact IsFP.of_mulEquiv Φ h

/-! ### Free products -/

section Coprod

variable {B₀ : Type u} [Group B₀] {B₁ : Type v} [Group B₁] {n₀ n₁ : ℕ}
  {S₀ : Set (FreeGroup (Fin n₀))} {S₁ : Set (FreeGroup (Fin n₁))}

/-- The free product relator set on `Fin (n₀ + n₁)`. -/
def coprodRels (S₀ : Set (FreeGroup (Fin n₀))) (S₁ : Set (FreeGroup (Fin n₁))) :
    Set (FreeGroup (Fin (n₀ + n₁))) :=
  FreeGroup.map (Fin.castAdd n₁) '' S₀ ∪ FreeGroup.map (Fin.natAdd n₀) '' S₁

/-- The left factor map into the presented free product. -/
noncomputable def coprodLeftAux (S₀ : Set (FreeGroup (Fin n₀))) (S₁ : Set (FreeGroup (Fin n₁))) :
    PresentedGroup S₀ →* PresentedGroup (coprodRels S₀ S₁) :=
  PresentedGroup.toGroup (f := fun i => of (Fin.castAdd n₁ i)) (by
    intro r hr
    rw [lift_of_map_eq_mk]
    exact PresentedGroup.one_of_mem (Or.inl ⟨r, hr, rfl⟩))

/-- The right factor map into the presented free product. -/
noncomputable def coprodRightAux (S₀ : Set (FreeGroup (Fin n₀))) (S₁ : Set (FreeGroup (Fin n₁))) :
    PresentedGroup S₁ →* PresentedGroup (coprodRels S₀ S₁) :=
  PresentedGroup.toGroup (f := fun i => of (Fin.natAdd n₀ i)) (by
    intro r hr
    rw [lift_of_map_eq_mk]
    exact PresentedGroup.one_of_mem (Or.inr ⟨r, hr, rfl⟩))

variable (ψ₀ : PresentedGroup S₀ ≃* B₀) (ψ₁ : PresentedGroup S₁ ≃* B₁)

/-- Generator assignment into `B₀ ∗ B₁`. -/
def coprodGens : Fin (n₀ + n₁) → Monoid.Coprod B₀ B₁ :=
  Fin.append (fun j => Monoid.Coprod.inl (ψ₀ (of j))) (fun j => Monoid.Coprod.inr (ψ₁ (of j)))

/-- Forward map. -/
noncomputable def coprodFwd : PresentedGroup (coprodRels S₀ S₁) →* Monoid.Coprod B₀ B₁ :=
  PresentedGroup.toGroup (f := coprodGens ψ₀ ψ₁) (by
    rintro r (⟨s, hs, rfl⟩ | ⟨s, hs, rfl⟩)
    · rw [lift_map']
      simp only [coprodGens, Fin.append_left]
      rw [lift_presentation ψ₀ (Monoid.Coprod.inl : B₀ →* Monoid.Coprod B₀ B₁),
        PresentedGroup.one_of_mem hs, map_one, map_one]
    · rw [lift_map']
      simp only [coprodGens, Fin.append_right]
      rw [lift_presentation ψ₁ (Monoid.Coprod.inr : B₁ →* Monoid.Coprod B₀ B₁),
        PresentedGroup.one_of_mem hs, map_one, map_one])

theorem coprodFwd_of (x : Fin (n₀ + n₁)) :
    coprodFwd ψ₀ ψ₁ (of x) = coprodGens ψ₀ ψ₁ x := by
  simp [coprodFwd, PresentedGroup.toGroup.of]

/-- Backward map. -/
noncomputable def coprodBwd : Monoid.Coprod B₀ B₁ →* PresentedGroup (coprodRels S₀ S₁) :=
  Monoid.Coprod.lift ((coprodLeftAux S₀ S₁).comp (ψ₀.symm : B₀ →* PresentedGroup S₀))
    ((coprodRightAux S₀ S₁).comp (ψ₁.symm : B₁ →* PresentedGroup S₁))

/-- **Presentation of a free product.** -/
noncomputable def coprodPresEquiv : PresentedGroup (coprodRels S₀ S₁) ≃* Monoid.Coprod B₀ B₁ :=
  MonoidHom.toMulEquiv (coprodFwd ψ₀ ψ₁) (coprodBwd ψ₀ ψ₁)
    (by
      apply PresentedGroup.ext
      intro x
      refine Fin.addCases (fun j => ?_) (fun j => ?_) x
      · simp [coprodFwd_of, coprodGens, coprodBwd, coprodLeftAux, PresentedGroup.toGroup.of]
      · simp [coprodFwd_of, coprodGens, coprodBwd, coprodRightAux, PresentedGroup.toGroup.of])
    (by
      apply Monoid.Coprod.hom_ext
      · apply hom_ext_presentation ψ₀
        intro j
        simp [coprodFwd_of, coprodGens, coprodBwd, coprodLeftAux, PresentedGroup.toGroup.of]
      · apply hom_ext_presentation ψ₁
        intro j
        simp [coprodFwd_of, coprodGens, coprodBwd, coprodRightAux, PresentedGroup.toGroup.of])

theorem coprodPresEquiv_of_castAdd (j : Fin n₀) :
    coprodPresEquiv ψ₀ ψ₁ (of (Fin.castAdd n₁ j)) = Monoid.Coprod.inl (ψ₀ (of j)) := by
  simp [coprodPresEquiv, coprodFwd_of, coprodGens]

theorem coprodPresEquiv_of_natAdd (j : Fin n₁) :
    coprodPresEquiv ψ₀ ψ₁ (of (Fin.natAdd n₀ j)) = Monoid.Coprod.inr (ψ₁ (of j)) := by
  simp [coprodPresEquiv, coprodFwd_of, coprodGens]

end Coprod

/-- The merged enumerator of a free product. -/
def coprodEnum {n₀ n₁ : ℕ} (e₀ : ℕ →. RawWord (Fin n₀)) (e₁ : ℕ →. RawWord (Fin n₁)) :
    ℕ →. RawWord (Fin (n₀ + n₁)) :=
  mergeEnum (extendEnum e₀ (Fin.castAdd n₁) []) (extendEnum e₁ (Fin.natAdd n₀) [])

theorem IsEnumerator.coprodEnum {R : Set ℕ} {n₀ n₁ : ℕ} {e₀ : ℕ →. RawWord (Fin n₀)}
    {e₁ : ℕ →. RawWord (Fin n₁)} (h₀ : IsEnumerator R e₀) (h₁ : IsEnumerator R e₁) :
    IsEnumerator R (TheoremA.RelPres.coprodEnum e₀ e₁) :=
  (h₀.extendEnum _ _).mergeEnum (h₁.extendEnum _ _)

theorem enumRelators_coprodEnum {n₀ n₁ : ℕ} (e₀ : ℕ →. RawWord (Fin n₀))
    (e₁ : ℕ →. RawWord (Fin n₁)) :
    enumRelators (coprodEnum e₀ e₁) = coprodRels (enumRelators e₀) (enumRelators e₁) := by
  simp [coprodEnum, enumRelators_mergeEnum, enumRelators_extendEnum, coprodRels]

/-- **`C_R` is closed under free products** (same oracle). -/
theorem ClassCR.coprod {R : Set ℕ} {B₀ B₁ : Type u} [Group B₀] [Group B₁] (h₀ : ClassCR R B₀)
    (h₁ : ClassCR R B₁) : ClassCR R (Monoid.Coprod B₀ B₁) := by
  obtain ⟨n₀, e₀, he₀, ⟨ψ₀⟩⟩ := h₀
  obtain ⟨n₁, e₁, he₁, ⟨ψ₁⟩⟩ := h₁
  refine ⟨n₀ + n₁, coprodEnum e₀ e₁, he₀.coprodEnum he₁, ⟨?_⟩⟩
  rw [enumRelators_coprodEnum]
  exact coprodPresEquiv ψ₀ ψ₁

/-- **`FP₂` is closed under free products** (for finite-alphabet presentations). -/
theorem isFP_two_coprod_of_pres {B₀ : Type u} [Group B₀] {B₁ : Type v} [Group B₁] {n₀ n₁ : ℕ}
    {S₀ : Set (FreeGroup (Fin n₀))} {S₁ : Set (FreeGroup (Fin n₁))}
    (ψ₀ : PresentedGroup S₀ ≃* B₀) (ψ₁ : PresentedGroup S₁ ≃* B₁) (h₀ : IsFP 2 B₀)
    (h₁ : IsFP 2 B₁) : IsFP 2 (Monoid.Coprod B₀ B₁) := by
  have := isFP_two_presentedGroup_two_sources_union_finite S₀ S₁
    (FreeGroup.map (Fin.castAdd n₁)) (FreeGroup.map (Fin.natAdd n₀)) ∅ Set.finite_empty
    (IsFP.of_mulEquiv ψ₀.symm h₀) (IsFP.of_mulEquiv ψ₁.symm h₁)
  rw [Set.union_empty] at this
  exact IsFP.of_mulEquiv (coprodPresEquiv ψ₀ ψ₁) this

end TheoremA.RelPres
