module

public import Mathlib.Algebra.Group.Subgroup.Pointwise
public import Mathlib.Algebra.Group.Int.Defs
public import Mathlib.Data.List.Chain

/-!
# Segment forms for subgroups generated by a family `x : ℤ → G`

A *segment form* is `(z₀, L)` with `L = [(s₁, b₁, z₁), …, (sₘ, bₘ, zₘ)]`, all `sₖ ≠ 0`, and it
evaluates to
`x 0 ^ z₀ * x s₁ ^ (±1) * x 0 ^ z₁ * ⋯ * x sₘ ^ (±1) * x 0 ^ zₘ`
(sign `+` iff `bₖ = true`).  It is *admissible* if a factor `x s ^ (±1)` is never followed,
with nothing in between (`zₖ = 0`), by the inverse factor `x s ^ (∓1)`.

`exists_segForm`: every element of `closure (range x)` has an admissible segment form.
-/

@[expose] public section

namespace TheoremA.Seg

variable {G : Type*} [Group G] (x : ℤ → G)

/-- A signed factor. -/
def sgn (g : G) (b : Bool) : G := if b then g else g⁻¹

/-- Evaluation of the tail of a segment form. -/
def tail : List (ℤ × Bool × ℤ) → G
  | [] => 1
  | e :: L => sgn (x e.1) e.2.1 * x 0 ^ e.2.2 * tail L

/-- Evaluation of a segment form. -/
def eval (z₀ : ℤ) (L : List (ℤ × Bool × ℤ)) : G := x 0 ^ z₀ * tail x L

/-- Admissibility. -/
def OK (L : List (ℤ × Bool × ℤ)) : Prop :=
  (∀ e ∈ L, e.1 ≠ 0) ∧
    L.IsChain (fun e₁ e₂ => e₁.2.2 = 0 → ¬ (e₁.1 = e₂.1 ∧ e₁.2.1 ≠ e₂.2.1))

theorem tail_append (L : List (ℤ × Bool × ℤ)) (e : ℤ × Bool × ℤ) :
    tail x (L ++ [e]) = tail x L * (sgn (x e.1) e.2.1 * x 0 ^ e.2.2) := by
  induction L with
  | nil => simp [tail]
  | cons f L ih => simp [tail, ih, mul_assoc]

theorem tail_concat_z (L : List (ℤ × Bool × ℤ)) (s : ℤ) (b : Bool) (z w : ℤ) :
    tail x (L ++ [(s, b, z + w)]) = tail x (L ++ [(s, b, z)]) * x 0 ^ w := by
  rw [tail_append, tail_append, zpow_add]; simp [mul_assoc]

/-- The admissibility chain condition for a list ending in a given entry. -/
theorem ok_concat {L : List (ℤ × Bool × ℤ)} {e f : ℤ × Bool × ℤ} (h : OK (L ++ [e]))
    (hf : f.1 ≠ 0) (hef : e.2.2 = 0 → ¬ (e.1 = f.1 ∧ e.2.1 ≠ f.2.1)) :
    OK (L ++ [e] ++ [f]) := by
  refine ⟨?_, ?_⟩
  · intro g hg
    rcases List.mem_append.1 hg with hg | hg
    · exact h.1 g hg
    · rw [List.mem_singleton] at hg; subst hg; exact hf
  · rw [List.isChain_append]
    refine ⟨h.2, List.isChain_singleton _, ?_⟩
    intro a ha b hb
    simp only [List.getLast?_append, List.getLast?_singleton, Option.some_or,
      Option.mem_def, Option.some.injEq, List.head?_cons] at ha hb
    subst ha; subst hb; exact hef

theorem ok_dropLast {L : List (ℤ × Bool × ℤ)} {e : ℤ × Bool × ℤ} (h : OK (L ++ [e])) :
    OK L :=
  ⟨fun g hg => h.1 g (List.mem_append_left _ hg), (List.isChain_append.1 h.2).1⟩

theorem ok_change_z {L : List (ℤ × Bool × ℤ)} {s : ℤ} {b : Bool} {z w : ℤ}
    (h : OK (L ++ [(s, b, z)])) : OK (L ++ [(s, b, w)]) := by
  refine ⟨?_, ?_⟩
  · intro g hg
    rcases List.mem_append.1 hg with hg | hg
    · exact h.1 g (List.mem_append_left _ hg)
    · rw [List.mem_singleton] at hg; subst hg
      exact h.1 (s, b, z) (by simp)
  · have h2 := List.isChain_append.1 h.2
    rw [List.isChain_append]
    refine ⟨h2.1, List.isChain_singleton _, ?_⟩
    intro a ha c hc
    simp only [List.head?_cons, Option.mem_def, Option.some.injEq] at hc
    subst hc
    exact h2.2.2 a ha (s, b, z) (by simp)

theorem sgn_zpow (g : G) (b : Bool) : sgn g b = g ^ (if b then (1 : ℤ) else -1) := by
  cases b <;> simp [sgn]

theorem eq_nil_or_concat' (L : List (ℤ × Bool × ℤ)) :
    L = [] ∨ ∃ L' s b z, L = L' ++ [(s, b, z)] := by
  rcases L.eq_nil_or_concat with h | ⟨L', ⟨s, b, z⟩, h⟩
  · exact Or.inl h
  · exact Or.inr ⟨L', s, b, z, by simp [h]⟩

/-- One step: multiply an admissible form by a signed generator. -/
theorem exists_segForm_mul (z₀ : ℤ) (L : List (ℤ × Bool × ℤ)) (hL : OK L) (s : ℤ) (b : Bool) :
    ∃ z₀' L', OK L' ∧ eval x z₀' L' = eval x z₀ L * sgn (x s) b := by
  by_cases hs : s = 0
  · subst hs
    rcases eq_nil_or_concat' L with rfl | ⟨L', s', b', z, rfl⟩
    · refine ⟨z₀ + (if b then 1 else -1), [], hL, ?_⟩
      simp [eval, tail, zpow_add, sgn_zpow]
    · refine ⟨z₀, L' ++ [(s', b', z + (if b then 1 else -1))], ok_change_z hL, ?_⟩
      simp only [eval, tail_concat_z, sgn_zpow, mul_assoc]
  · rcases eq_nil_or_concat' L with rfl | ⟨L', s', b', z, rfl⟩
    · refine ⟨z₀, [(s, b, 0)], ⟨by simpa using hs, List.isChain_singleton _⟩, ?_⟩
      simp [eval, tail]
    · by_cases hc : z = 0 ∧ s' = s ∧ b' ≠ b
      · obtain ⟨rfl, rfl, hb⟩ := hc
        refine ⟨z₀, L', ok_dropLast hL, ?_⟩
        simp only [eval, tail_append, mul_assoc, zpow_zero, one_mul]
        congr 1
        have : sgn (x s') b' * sgn (x s') b = 1 := by
          cases b <;> cases b' <;> simp_all [sgn]
        rw [this, mul_one]
      · refine ⟨z₀, L' ++ [(s', b', z)] ++ [(s, b, 0)], ok_concat hL hs ?_, ?_⟩
        · intro hz h
          exact hc ⟨hz, h.1, h.2⟩
        · simp only [eval, tail_append, zpow_zero, mul_one, mul_assoc]

/-- **Existence of admissible segment forms.** -/
theorem exists_segForm {g : G} (hg : g ∈ Subgroup.closure (Set.range x)) :
    ∃ z₀ L, OK L ∧ eval x z₀ L = g := by
  induction hg using Subgroup.closure_induction_right with
  | one => exact ⟨0, [], ⟨by simp, List.IsChain.nil⟩, by simp [eval, tail]⟩
  | mul_right g _ y hy ih =>
    obtain ⟨s, rfl⟩ := hy
    obtain ⟨z₀, L, hL, rfl⟩ := ih
    exact exists_segForm_mul x z₀ L hL s true
  | mul_inv_cancel g _ y hy ih =>
    obtain ⟨s, rfl⟩ := hy
    obtain ⟨z₀, L, hL, rfl⟩ := ih
    exact exists_segForm_mul x z₀ L hL s false

/-- Segment forms are natural. -/
theorem map_tail {H : Type*} [Group H] (f : G →* H) (L : List (ℤ × Bool × ℤ)) :
    f (tail x L) = tail (fun s => f (x s)) L := by
  induction L with
  | nil => simp [tail]
  | cons e L ih => simp [tail, ih, sgn]; split_ifs <;> simp [ih]

theorem map_eval {H : Type*} [Group H] (f : G →* H) (z₀ : ℤ) (L : List (ℤ × Bool × ℤ)) :
    f (eval x z₀ L) = eval (fun s => f (x s)) z₀ L := by
  simp [eval, map_tail]

/-- The value of a segment form lies in the subgroup generated by the factors used. -/
theorem eval_mem {H : Subgroup G} (z₀ : ℤ) (L : List (ℤ × Bool × ℤ)) (h0 : x 0 ∈ H)
    (hL : ∀ e ∈ L, x e.1 ∈ H) : eval x z₀ L ∈ H := by
  refine H.mul_mem (H.zpow_mem h0 _) ?_
  induction L with
  | nil => exact H.one_mem
  | cons e L ih =>
    refine H.mul_mem (H.mul_mem ?_ (H.zpow_mem h0 _)) (ih fun f hf => hL f (by simp [hf]))
    have := hL e (by simp)
    unfold sgn; split_ifs
    · exact this
    · exact H.inv_mem this

end TheoremA.Seg
